# Example script for Hackathon

Within each cycle of active learning, you can:

1. Collect training data (original training data + your query data).

2. Train a prediction model to predict the DMS_score for each mutant (e.g., M0A).

3. Use the trained model to predict the score for all mutant in the test set.

4. Select query mutants for next round based on certain criteria. You may want to make sure you don't query the same mutant twice as you only have a limited chances of making queries in total.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, Dataset
import random
from copy import deepcopy
import pandas as pd
from scipy.stats import spearmanr
import argparse
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

## 1. collect training data

Upload `sequence.fasta`, `train.csv`, and `test.csv` to the current runtime:

1. click the folder icon on the left

2. click the upload icon and upload the files to the current directory

In [ ]:
with open('sequence.fasta', 'r') as f:
  data = f.readlines()

sequence_wt = data[1].strip()
sequence_wt

'MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLREKMRRRLESGDKWFSLEFFPPRTAEGAVNLISRFDRMAAGGPLYIDVTWHPAGDPGSDKETSSMMIASTAVNYCGLETILHMTCCRQRLEEITGHLHKAKQLGLKNIMALRGDPIGDQWEEEEGGFNYAVDLVKHIRSEFGDYFDICVAGYPKGHPEAGSFEADLKHLKEKVSAGADFIITQLFFEADTFFRFVKACTDMGITCPIVPGIFPIQGYHSLRQLVKLSKLEVPQEIKDVIEPIKDNDAAIRNYGIELAVSLCQELLASGLVPGLHFYTLNREMATTEVLKRLGMWTEDPRRPLPWALSAHPKRREEDVRPIFWASRPKSYIYRTQEWDEFPNGRWGNSSSPAFGELKDYYLFYLKSKSPKEELLKMWGEELTSEESVFEVFVLYLSGEPNRNGHKVTCLPWNDEPLAAETSLLKEELLRVNRQGILTINSQPNINGKPSSDPIVGWGPSGGYVFQKAYLEFFTSRETAEALLQVLKKYELRVNYHLVNVKGENITNAPELQPNAVTWGIFPGREIIQPTVVDPVSFMFWKDEAFALWIERWGKLYEEESPSRTIIQYIHDNYFLVNLVDNDFPLDNCLWQVVEDTLELLNRPTQNARETEAP'

In [ ]:
len(sequence_wt)

656

In [ ]:
def get_mutated_sequence(mut, sequence_wt):
  wt, pos, mt = mut[0], int(mut[1:-1]), mut[-1]
  #wt is first char
  #pos is second char to second to last char
  #mt is last char

  #Each row in the dataset contains:
  #First character: Wild-type amino acid (e.g., M)
  #Number: 0-based position in the sequence (e.g., 0, 5, 10)
  #Last character: Mutated amino acid (e.g., A, C, T, V)

  sequence = deepcopy(sequence_wt)
  #sequence is wildtype (most common natural type) of the target protein

  #returns the mutated version of the wildtype
  return sequence[:pos]+mt+sequence[pos+1:]

In [ ]:
df_train = pd.read_csv('train.csv')
df_train['sequence'] = df_train.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_train

     mutant  DMS_score                                           sequence
0       M0Y   0.273000  YVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1       M0W   0.285700  WVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
2       M0V   0.215300  VVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
3       M0T   0.312200  TVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
4       M0S   0.218000  SVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
...     ...        ...                                                ...
1435  Q647F   0.912895  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1436  N648F   0.910830  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1437  A649F   0.983052  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1438  R650F   0.840307  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1439  E651F   0.952191  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...

[1440 rows x 3 columns]

In [ ]:
df_test = pd.read_csv('test.csv')
df_test['sequence'] = df_test.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_test

      mutant                                           sequence
0        V1D  MDNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1        V1Y  MYNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
2        V1C  MCNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
3        V1A  MANEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
4        V1E  MENEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
...      ...                                                ...
11319  P655S  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11320  P655T  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11321  P655V  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11322  P655A  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11323  P655W  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...

[11324 rows x 2 columns]

In [ ]:
# TODO: integrate the query data that you acquired each round into df_train

## 2. Train a prediction model

Here, we provided a linear regression model and used one-hot encoding to encode each variant. You would need to build your own model to achieve better performances.

Hint: you can perform cross-validation on the training set to evaluate your predictor before making predictions on the test set.

In [ ]:
'''hyperparameters'''

seq_length = 656
seed = 0 # seed for splitting the validation set
val_ratio = 0.2 # proportion of validation set

In [ ]:
class ProteinDataset(Dataset):
    def __init__(self, df, istrain=True):

        alphabet = 'ACDEFGHIKLMNPQRSTVWY'
        map_a2i = {j:i for i,j in enumerate(alphabet)}
        map_i2a = {i:j for i,j in enumerate(alphabet)}

        self.df = df

        self.num_samples = len(self.df)
        self.seq_length = len(self.df.sequence.values[0])
        self.num_channels = 20

        # TODO: replace one-hot encodings with your own encodings
        self.encodings = np.zeros((self.num_samples, 21)).astype(np.float32)
        self.targets = np.zeros(self.num_samples).astype(np.float32)

        if istrain:
            for it, (mutation, target) in enumerate(self.df[['mutant', 'DMS_score']].values):
                index = int(mutation[1:-1])
                newVal = mutation[-1]
                self.encodings[it, 0] = index / seq_length
                self.encodings[it, map_a2i[newVal] + 1] = 1
                self.targets[it] = target
        else:
            for it, mutation in enumerate(self.df['mutant'].values):
                index = int(mutation[1:-1])
                newVal = mutation[-1]
                self.encodings[it, 0] = index / seq_length
                self.encodings[it, map_a2i[newVal] + 1] = 1


    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return torch.tensor(self.encodings[idx]), torch.tensor(self.targets[idx])

In [ ]:
train_dataset = ProteinDataset(df_train)
test_dataset = ProteinDataset(df_test, istrain=False)

# split validation set
train_dataset, val_dataset = train_test_split(train_dataset, test_size=val_ratio, random_state=seed, shuffle=True)

# TODO: revise according to your own model
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [ ]:
#My own class for predictive model

class ProteinNet(nn.Module):
    def __init__(self, inputDim):
        super(ProteinNet, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(inputDim, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(.2),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.layers(x)

In [ ]:
#Train time
def train(model, train_loader, val_loader):
  epochs = 1000
  lr = .001
  criterion = nn.MSELoss()
  optimizer = optim.Adam(model.parameters(), lr)

  for epoch in range(epochs):
      model.train()
      lossTotal = 0
      for X, y in train_loader:
          X = X.to(device)
          y = y.to(device)
          optimizer.zero_grad()
          predictions = model(X.float())
          loss = criterion(predictions, y.float().view(-1, 1))
          loss.backward()
          optimizer.step()
          lossTotal += loss.item()
      with torch.no_grad():
          model.eval()
          lossValTotal = 0
          valPreds = []
          valTargets = []
          for X, y in val_loader:
              X = X.to(device)
              y = y.to(device)
              predictions = model(X.float())
              loss = criterion(predictions, y.float().view(-1, 1))
              lossValTotal += loss.item()

              valPreds.extend(predictions.cpu().numpy().flatten())
              valTargets.extend(y.cpu().numpy().flatten())
          spearmanVal = spearmanr(valTargets, valPreds)[0]
      print(f"Epoch {epoch+1}/{epochs}, Loss: {lossTotal/len(train_loader)}, Val Loss: {lossValTotal/len(val_loader)}, SpearMan: {spearmanVal:.4f}")

In [ ]:
# TODO: build your own prediction model to replace linear regression
# Hint: don't forget to use the validation set: you can either integrate the validation data into the training set or use it separately for early stopping

X_train, y_train = next(iter(train_loader))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

inputDim = X_train.shape[1]
model1 = ProteinNet(inputDim).to(device)
model2 = ProteinNet(inputDim).to(device)
model3 = ProteinNet(inputDim).to(device)
model4 = ProteinNet(inputDim).to(device)
model5 = ProteinNet(inputDim).to(device)

train(model1, train_loader, val_loader)
train(model2, train_loader, val_loader)
train(model3, train_loader, val_loader)
train(model4, train_loader, val_loader)
train(model5, train_loader, val_loader)

Epoch 1/1000, Loss: 0.10917475240098105, Val Loss: 0.09333404749631882, SpearMan: 0.2773
Epoch 2/1000, Loss: 0.08800392225384712, Val Loss: 0.07910502552986146, SpearMan: 0.3719
Epoch 3/1000, Loss: 0.07693222227195899, Val Loss: 0.07045345604419709, SpearMan: 0.3682
Epoch 4/1000, Loss: 0.06887099788420731, Val Loss: 0.06429005786776543, SpearMan: 0.3850
Epoch 5/1000, Loss: 0.0636555136491855, Val Loss: 0.06046821847558022, SpearMan: 0.3772
Epoch 6/1000, Loss: 0.05994926103287273, Val Loss: 0.057335230708122256, SpearMan: 0.3791
Epoch 7/1000, Loss: 0.056536730378866196, Val Loss: 0.05485475659370422, SpearMan: 0.3668
Epoch 8/1000, Loss: 0.05439011628429095, Val Loss: 0.05195599868893623, SpearMan: 0.3615
Epoch 9/1000, Loss: 0.052796038488547005, Val Loss: 0.04989998787641525, SpearMan: 0.3569
Epoch 10/1000, Loss: 0.050392567076616816, Val Loss: 0.04723895154893398, SpearMan: 0.3556
Epoch 11/1000, Loss: 0.04912015702575445, Val Loss: 0.04637010470032692, SpearMan: 0.3572
Epoch 12/1000, Loss: 0.04723016048471133, Val Loss: 0.04512964002788067, SpearMan: 0.3536
Epoch 13/1000, Loss: 0.0468660325018896, Val Loss: 0.04452287517488003, SpearMan: 0.3575
Epoch 14/1000, Loss: 0.0461145993322134, Val Loss: 0.044358471408486366, SpearMan: 0.3525
Epoch 15/1000, Loss: 0.04565735792534219, Val Loss: 0.04410553872585297, SpearMan: 0.3587
Epoch 16/1000, Loss: 0.04522068053483963, Val Loss: 0.044174833223223686, SpearMan: 0.3606
Epoch 17/1000, Loss: 0.045321058481931686, Val Loss: 0.04391556642949581, SpearMan: 0.3645
Epoch 18/1000, Loss: 0.04463961668726471, Val Loss: 0.04362647496163845, SpearMan: 0.3684
Epoch 19/1000, Loss: 0.04371533253126674, Val Loss: 0.04343206360936165, SpearMan: 0.3697
Epoch 20/1000, Loss: 0.04395429841760132, Val Loss: 0.04337347261607647, SpearMan: 0.3759
Epoch 21/1000, Loss: 0.04404144330571095, Val Loss: 0.04369409717619419, SpearMan: 0.3784
Epoch 22/1000, Loss: 0.04376209630734391, Val Loss: 0.043194962292909624, SpearMan: 0.3832
Epoch 23/1000, Loss: 0.0433745752606127, Val Loss: 0.0430244404822588, SpearMan: 0.3806
Epoch 24/1000, Loss: 0.04377348596851031, Val Loss: 0.042902227491140366, SpearMan: 0.3917
Epoch 25/1000, Loss: 0.04339181693891684, Val Loss: 0.04274909384548664, SpearMan: 0.3855
Epoch 26/1000, Loss: 0.042774920558763876, Val Loss: 0.04259822480380535, SpearMan: 0.3945
Epoch 27/1000, Loss: 0.042630296821395554, Val Loss: 0.04227993004024029, SpearMan: 0.3995
Epoch 28/1000, Loss: 0.04245921255399784, Val Loss: 0.0422647625207901, SpearMan: 0.3999
Epoch 29/1000, Loss: 0.04254612047225237, Val Loss: 0.041723576933145524, SpearMan: 0.4086
Epoch 30/1000, Loss: 0.04306799018134674, Val Loss: 0.04203779436647892, SpearMan: 0.4147
Epoch 31/1000, Loss: 0.04209164229946004, Val Loss: 0.04213243462145329, SpearMan: 0.4144
Epoch 32/1000, Loss: 0.04203858981943793, Val Loss: 0.04186881817877293, SpearMan: 0.4243
Epoch 33/1000, Loss: 0.04127994190073676, Val Loss: 0.04162279032170772, SpearMan: 0.4239
Epoch 34/1000, Loss: 0.040481833948029414, Val Loss: 0.04164552241563797, SpearMan: 0.4333
Epoch 35/1000, Loss: 0.040928395465016365, Val Loss: 0.041405601799488066, SpearMan: 0.4418
Epoch 36/1000, Loss: 0.04168629853261842, Val Loss: 0.040964645147323606, SpearMan: 0.4408
Epoch 37/1000, Loss: 0.04144587398817142, Val Loss: 0.04132367521524429, SpearMan: 0.4421
Epoch 38/1000, Loss: 0.04161072977715068, Val Loss: 0.04107021763920784, SpearMan: 0.4384
Epoch 39/1000, Loss: 0.04172851134919458, Val Loss: 0.04108516797423363, SpearMan: 0.4420
Epoch 40/1000, Loss: 0.041343576481772795, Val Loss: 0.04096204228699207, SpearMan: 0.4524
Epoch 41/1000, Loss: 0.04056474400891198, Val Loss: 0.04066543765366078, SpearMan: 0.4351
Epoch 42/1000, Loss: 0.04047239675290055, Val Loss: 0.04056908674538136, SpearMan: 0.4532
Epoch 43/1000, Loss: 0.04031727400918802, Val Loss: 0.040728821977972986, SpearMan: 0.4593
Epoch 44/1000, Loss: 0.041095722259746656, Val Loss: 0.040601597726345064, SpearMan: 0.4569
Epoch 45/1000, Loss: 0.04086369451963239, Val Loss: 0.04083957299590111, SpearMan: 0.4619
Epoch 46/1000, Loss: 0.04031589844574531, Val Loss: 0.04100392684340477, SpearMan: 0.4653
Epoch 47/1000, Loss: 0.0402136022845904, Val Loss: 0.04068670347332955, SpearMan: 0.4745
Epoch 48/1000, Loss: 0.040547466526428856, Val Loss: 0.04024851731956005, SpearMan: 0.4752
Epoch 49/1000, Loss: 0.04062352153576083, Val Loss: 0.04073966778814793, SpearMan: 0.4714
Epoch 50/1000, Loss: 0.040150296253462635, Val Loss: 0.04037246741354465, SpearMan: 0.4784
Epoch 51/1000, Loss: 0.03978898531446854, Val Loss: 0.040410174429416655, SpearMan: 0.4803
Epoch 52/1000, Loss: 0.04021106463753515, Val Loss: 0.04005205892026424, SpearMan: 0.4843
Epoch 53/1000, Loss: 0.040948164442347154, Val Loss: 0.04021295979619026, SpearMan: 0.4898
Epoch 54/1000, Loss: 0.04013611148628923, Val Loss: 0.04017665386199951, SpearMan: 0.4846
Epoch 55/1000, Loss: 0.04012531662980715, Val Loss: 0.04045477956533432, SpearMan: 0.4963
Epoch 56/1000, Loss: 0.039220908760196634, Val Loss: 0.040246526896953586, SpearMan: 0.4977
Epoch 57/1000, Loss: 0.03922341981281837, Val Loss: 0.04043110162019729, SpearMan: 0.5030
Epoch 58/1000, Loss: 0.03931038650787539, Val Loss: 0.04022256210446358, SpearMan: 0.4987
Epoch 59/1000, Loss: 0.040848584949142404, Val Loss: 0.040064787119627, SpearMan: 0.5036
Epoch 60/1000, Loss: 0.039304486475884914, Val Loss: 0.04046327620744705, SpearMan: 0.5133
Epoch 61/1000, Loss: 0.03906695679244068, Val Loss: 0.03998584523797035, SpearMan: 0.5039
Epoch 62/1000, Loss: 0.039427959360182285, Val Loss: 0.0401858851313591, SpearMan: 0.5090
Epoch 63/1000, Loss: 0.03960070386528969, Val Loss: 0.0399133063852787, SpearMan: 0.5123
Epoch 64/1000, Loss: 0.03936348741667138, Val Loss: 0.03999573364853859, SpearMan: 0.5080
Epoch 65/1000, Loss: 0.039643381308350295, Val Loss: 0.03977750390768051, SpearMan: 0.5158
Epoch 66/1000, Loss: 0.03940793861531549, Val Loss: 0.039824987575411794, SpearMan: 0.5102
Epoch 67/1000, Loss: 0.040538750485413604, Val Loss: 0.040614145994186404, SpearMan: 0.5090
Epoch 68/1000, Loss: 0.04000784187681145, Val Loss: 0.040163978561758996, SpearMan: 0.5122
Epoch 69/1000, Loss: 0.03882975410670042, Val Loss: 0.039856497570872305, SpearMan: 0.5139
Epoch 70/1000, Loss: 0.039786526208950415, Val Loss: 0.04039319381117821, SpearMan: 0.5207
Epoch 71/1000, Loss: 0.039269941134585276, Val Loss: 0.039690082892775536, SpearMan: 0.5198
Epoch 72/1000, Loss: 0.03879274003621605, Val Loss: 0.040148307010531424, SpearMan: 0.5207
Epoch 73/1000, Loss: 0.03952153316802449, Val Loss: 0.03998545259237289, SpearMan: 0.5281
Epoch 74/1000, Loss: 0.03973895445879963, Val Loss: 0.039506806433200835, SpearMan: 0.5283
Epoch 75/1000, Loss: 0.03914739708933565, Val Loss: 0.03984036445617676, SpearMan: 0.5340
Epoch 76/1000, Loss: 0.03954325316266881, Val Loss: 0.03977510333061218, SpearMan: 0.5301
Epoch 77/1000, Loss: 0.038913752883672714, Val Loss: 0.03948512934148311, SpearMan: 0.5270
Epoch 78/1000, Loss: 0.03951627005719476, Val Loss: 0.03940698727965355, SpearMan: 0.5244
Epoch 79/1000, Loss: 0.03949158338622914, Val Loss: 0.040215080603957176, SpearMan: 0.5232
Epoch 80/1000, Loss: 0.039230066558553114, Val Loss: 0.039685184881091115, SpearMan: 0.5238
Epoch 81/1000, Loss: 0.03894011831531922, Val Loss: 0.039742646366357805, SpearMan: 0.5300
Epoch 82/1000, Loss: 0.03887044296910366, Val Loss: 0.039882273972034456, SpearMan: 0.5238
Epoch 83/1000, Loss: 0.039275651797652245, Val Loss: 0.0401068102568388, SpearMan: 0.5259
Epoch 84/1000, Loss: 0.03919914044025871, Val Loss: 0.039782175421714784, SpearMan: 0.5308
Epoch 85/1000, Loss: 0.03944913691116704, Val Loss: 0.040037135034799574, SpearMan: 0.5408
Epoch 86/1000, Loss: 0.03885262728565269, Val Loss: 0.03988162130117416, SpearMan: 0.5348
Epoch 87/1000, Loss: 0.03800647519528866, Val Loss: 0.03982698768377304, SpearMan: 0.5421
Epoch 88/1000, Loss: 0.03851255391620927, Val Loss: 0.03922472298145294, SpearMan: 0.5504
Epoch 89/1000, Loss: 0.038717484205133386, Val Loss: 0.039849312603473665, SpearMan: 0.5493
Epoch 90/1000, Loss: 0.038492650207546025, Val Loss: 0.03905908651649952, SpearMan: 0.5608
Epoch 91/1000, Loss: 0.03823327449046903, Val Loss: 0.0395760715007782, SpearMan: 0.5498
Epoch 92/1000, Loss: 0.03835910465568304, Val Loss: 0.039821992814540866, SpearMan: 0.5513
Epoch 93/1000, Loss: 0.038729914360576205, Val Loss: 0.03968016766011715, SpearMan: 0.5443
Epoch 94/1000, Loss: 0.03907298907223675, Val Loss: 0.03991865441203117, SpearMan: 0.5427
Epoch 95/1000, Loss: 0.038823049515485764, Val Loss: 0.03965225294232368, SpearMan: 0.5492
Epoch 96/1000, Loss: 0.038704132868183985, Val Loss: 0.039603883773088454, SpearMan: 0.5450
Epoch 97/1000, Loss: 0.039334579991797604, Val Loss: 0.03960355967283249, SpearMan: 0.5477
Epoch 98/1000, Loss: 0.03846414739059077, Val Loss: 0.03943048864603042, SpearMan: 0.5482
Epoch 99/1000, Loss: 0.03862808758599891, Val Loss: 0.04007226303219795, SpearMan: 0.5546
Epoch 100/1000, Loss: 0.03867088837756051, Val Loss: 0.03995382785797119, SpearMan: 0.5460
Epoch 101/1000, Loss: 0.03858479319347276, Val Loss: 0.04015258140861988, SpearMan: 0.5492
Epoch 102/1000, Loss: 0.0381812308397558, Val Loss: 0.039700116217136386, SpearMan: 0.5496
Epoch 103/1000, Loss: 0.038668458039561905, Val Loss: 0.03978326246142387, SpearMan: 0.5516
Epoch 104/1000, Loss: 0.03893703988028897, Val Loss: 0.038911495357751846, SpearMan: 0.5634
Epoch 105/1000, Loss: 0.038559903080264725, Val Loss: 0.0402083158493042, SpearMan: 0.5596
Epoch 106/1000, Loss: 0.03807430052094989, Val Loss: 0.03952973894774914, SpearMan: 0.5598
Epoch 107/1000, Loss: 0.038367730668849416, Val Loss: 0.03919766396284104, SpearMan: 0.5543
Epoch 108/1000, Loss: 0.038653170896901026, Val Loss: 0.039560487121343614, SpearMan: 0.5597
Epoch 109/1000, Loss: 0.038952084051238164, Val Loss: 0.03959025628864765, SpearMan: 0.5634
Epoch 110/1000, Loss: 0.038728555043538414, Val Loss: 0.03938524201512337, SpearMan: 0.5639
Epoch 111/1000, Loss: 0.03779147451536523, Val Loss: 0.03982959054410458, SpearMan: 0.5584
Epoch 112/1000, Loss: 0.03884087958269649, Val Loss: 0.03945591077208519, SpearMan: 0.5593
Epoch 113/1000, Loss: 0.0382913068557779, Val Loss: 0.03984474502503872, SpearMan: 0.5598
Epoch 114/1000, Loss: 0.03857991844415665, Val Loss: 0.039886119216680525, SpearMan: 0.5631
Epoch 115/1000, Loss: 0.038374596275389194, Val Loss: 0.03955430462956429, SpearMan: 0.5609
Epoch 116/1000, Loss: 0.03820914516432418, Val Loss: 0.039964410662651065, SpearMan: 0.5665
Epoch 117/1000, Loss: 0.03823383142136865, Val Loss: 0.03962131254374981, SpearMan: 0.5666
Epoch 118/1000, Loss: 0.03839707084827953, Val Loss: 0.03915995769202709, SpearMan: 0.5688
Epoch 119/1000, Loss: 0.037817959052821, Val Loss: 0.03946002796292305, SpearMan: 0.5651
Epoch 120/1000, Loss: 0.03840699843648407, Val Loss: 0.03928854912519455, SpearMan: 0.5708
Epoch 121/1000, Loss: 0.03844912867579195, Val Loss: 0.039699915796518326, SpearMan: 0.5731
Epoch 122/1000, Loss: 0.038220434139172234, Val Loss: 0.039228569343686105, SpearMan: 0.5709
Epoch 123/1000, Loss: 0.037521864391035505, Val Loss: 0.03986563719809055, SpearMan: 0.5702
Epoch 124/1000, Loss: 0.03883491601381037, Val Loss: 0.03890778236091137, SpearMan: 0.5796
Epoch 125/1000, Loss: 0.03923479374498129, Val Loss: 0.039197668060660364, SpearMan: 0.5682
Epoch 126/1000, Loss: 0.03815817553550005, Val Loss: 0.03979692682623863, SpearMan: 0.5668
Epoch 127/1000, Loss: 0.03810623764163918, Val Loss: 0.039908939972519875, SpearMan: 0.5790
Epoch 128/1000, Loss: 0.03791959221578307, Val Loss: 0.03975626081228256, SpearMan: 0.5701
Epoch 129/1000, Loss: 0.038291867822408676, Val Loss: 0.03966499678790569, SpearMan: 0.5760
Epoch 130/1000, Loss: 0.038261392464240394, Val Loss: 0.03972218707203865, SpearMan: 0.5795
Epoch 131/1000, Loss: 0.038049094999829926, Val Loss: 0.03977898582816124, SpearMan: 0.5794
Epoch 132/1000, Loss: 0.03786621791207128, Val Loss: 0.03904155232012272, SpearMan: 0.5865
Epoch 133/1000, Loss: 0.03837311495509413, Val Loss: 0.039483127743005754, SpearMan: 0.5830
Epoch 134/1000, Loss: 0.03807249220295085, Val Loss: 0.0392999030649662, SpearMan: 0.5845
Epoch 135/1000, Loss: 0.03808322000420756, Val Loss: 0.03955209627747536, SpearMan: 0.5804
Epoch 136/1000, Loss: 0.03752833139151335, Val Loss: 0.03896595500409603, SpearMan: 0.5789
Epoch 137/1000, Loss: 0.03745697645677461, Val Loss: 0.039104710519313815, SpearMan: 0.5865
Epoch 138/1000, Loss: 0.03780483930475182, Val Loss: 0.03937910981476307, SpearMan: 0.5815
Epoch 139/1000, Loss: 0.0378312925911612, Val Loss: 0.03908033743500709, SpearMan: 0.5874
Epoch 140/1000, Loss: 0.03714804992907577, Val Loss: 0.03909383863210678, SpearMan: 0.5778
Epoch 141/1000, Loss: 0.037813366701205574, Val Loss: 0.039505400136113165, SpearMan: 0.5858
Epoch 142/1000, Loss: 0.038058599871065885, Val Loss: 0.0389366690069437, SpearMan: 0.5852
Epoch 143/1000, Loss: 0.03772113182478481, Val Loss: 0.03947335593402386, SpearMan: 0.5747
Epoch 144/1000, Loss: 0.037458119086093374, Val Loss: 0.03974980041384697, SpearMan: 0.5656
Epoch 145/1000, Loss: 0.03758325996912188, Val Loss: 0.0394519679248333, SpearMan: 0.5747
Epoch 146/1000, Loss: 0.037679612533085875, Val Loss: 0.039908143877983096, SpearMan: 0.5782
Epoch 147/1000, Loss: 0.03777511604130268, Val Loss: 0.03948214314877987, SpearMan: 0.5840
Epoch 148/1000, Loss: 0.036975230297280684, Val Loss: 0.039580801874399184, SpearMan: 0.5824
Epoch 149/1000, Loss: 0.037647397360867925, Val Loss: 0.03941034078598023, SpearMan: 0.5749
Epoch 150/1000, Loss: 0.0373736455415686, Val Loss: 0.03897021040320396, SpearMan: 0.5836
Epoch 151/1000, Loss: 0.037476905414627656, Val Loss: 0.03943788111209869, SpearMan: 0.5913
Epoch 152/1000, Loss: 0.03707001513491074, Val Loss: 0.03959349095821381, SpearMan: 0.5830
Epoch 153/1000, Loss: 0.03662785349620713, Val Loss: 0.0392128448933363, SpearMan: 0.5790
Epoch 154/1000, Loss: 0.03753297020577722, Val Loss: 0.0390368927270174, SpearMan: 0.5820
Epoch 155/1000, Loss: 0.03768380110462507, Val Loss: 0.03897479996085167, SpearMan: 0.5876
Epoch 156/1000, Loss: 0.03750772184381882, Val Loss: 0.03934971056878567, SpearMan: 0.5859
Epoch 157/1000, Loss: 0.03759742538548178, Val Loss: 0.039291194453835485, SpearMan: 0.5842
Epoch 158/1000, Loss: 0.03755256730235285, Val Loss: 0.03906688466668129, SpearMan: 0.5855
Epoch 159/1000, Loss: 0.03704698456244336, Val Loss: 0.0392042987048626, SpearMan: 0.5828
Epoch 160/1000, Loss: 0.03775271545681688, Val Loss: 0.03956739529967308, SpearMan: 0.5801
Epoch 161/1000, Loss: 0.03733402563052045, Val Loss: 0.03941616043448448, SpearMan: 0.5771
Epoch 162/1000, Loss: 0.03735819634877973, Val Loss: 0.03966376893222332, SpearMan: 0.5772
Epoch 163/1000, Loss: 0.037229876758323774, Val Loss: 0.039578840509057044, SpearMan: 0.5884
Epoch 164/1000, Loss: 0.037368552966250315, Val Loss: 0.03925495967268944, SpearMan: 0.5911
Epoch 165/1000, Loss: 0.03715733573254612, Val Loss: 0.03890594206750393, SpearMan: 0.5929
Epoch 166/1000, Loss: 0.03702770991043912, Val Loss: 0.039582672715187076, SpearMan: 0.5899
Epoch 167/1000, Loss: 0.03737039429446062, Val Loss: 0.039399667829275134, SpearMan: 0.5856
Epoch 168/1000, Loss: 0.036910108394092984, Val Loss: 0.039393947646021846, SpearMan: 0.5937
Epoch 169/1000, Loss: 0.037045006536775164, Val Loss: 0.039749960601329806, SpearMan: 0.5934
Epoch 170/1000, Loss: 0.03716764526648654, Val Loss: 0.039329837635159494, SpearMan: 0.5948
Epoch 171/1000, Loss: 0.03762906448294719, Val Loss: 0.03890371695160866, SpearMan: 0.5994
Epoch 172/1000, Loss: 0.03692294222613176, Val Loss: 0.03912801519036293, SpearMan: 0.5942
Epoch 173/1000, Loss: 0.03765122861497932, Val Loss: 0.0393691997975111, SpearMan: 0.5869
Epoch 174/1000, Loss: 0.03741029349880086, Val Loss: 0.039394077658653257, SpearMan: 0.5855
Epoch 175/1000, Loss: 0.036684159810344376, Val Loss: 0.039292148500680926, SpearMan: 0.5957
Epoch 176/1000, Loss: 0.03720895873589648, Val Loss: 0.03969296514987945, SpearMan: 0.5888
Epoch 177/1000, Loss: 0.03794859080678887, Val Loss: 0.03947642631828785, SpearMan: 0.5899
Epoch 178/1000, Loss: 0.03761363195048438, Val Loss: 0.0392269641160965, SpearMan: 0.5901
Epoch 179/1000, Loss: 0.03734263156851133, Val Loss: 0.038929450884461404, SpearMan: 0.5925
Epoch 180/1000, Loss: 0.036725392979052335, Val Loss: 0.03901844806969166, SpearMan: 0.6021
Epoch 181/1000, Loss: 0.03684569688306914, Val Loss: 0.0390315618366003, SpearMan: 0.5983
Epoch 182/1000, Loss: 0.03695367090404034, Val Loss: 0.03924021236598492, SpearMan: 0.5964
Epoch 183/1000, Loss: 0.037451974116265774, Val Loss: 0.03912006840109825, SpearMan: 0.5881
Epoch 184/1000, Loss: 0.03755311492002673, Val Loss: 0.0391697820276022, SpearMan: 0.5907
Epoch 185/1000, Loss: 0.03738270110140244, Val Loss: 0.03875930458307266, SpearMan: 0.5931
Epoch 186/1000, Loss: 0.03705953175408973, Val Loss: 0.039196787774562834, SpearMan: 0.5880
Epoch 187/1000, Loss: 0.03649797083603011, Val Loss: 0.03925227336585522, SpearMan: 0.5881
Epoch 188/1000, Loss: 0.03717426138205661, Val Loss: 0.039446213468909266, SpearMan: 0.5862
Epoch 189/1000, Loss: 0.037172550025085606, Val Loss: 0.03901110552251339, SpearMan: 0.5979
Epoch 190/1000, Loss: 0.03805503280212482, Val Loss: 0.03891203105449677, SpearMan: 0.5958
Epoch 191/1000, Loss: 0.03625711343354649, Val Loss: 0.03870556727051735, SpearMan: 0.5973
Epoch 192/1000, Loss: 0.03737504697508282, Val Loss: 0.03901613727211952, SpearMan: 0.5912
Epoch 193/1000, Loss: 0.03697783199863301, Val Loss: 0.039188045635819437, SpearMan: 0.5917
Epoch 194/1000, Loss: 0.03693743474367592, Val Loss: 0.03948931582272053, SpearMan: 0.5954
Epoch 195/1000, Loss: 0.03702989137834973, Val Loss: 0.03867193907499313, SpearMan: 0.5934
Epoch 196/1000, Loss: 0.03697591988990704, Val Loss: 0.03915078304708004, SpearMan: 0.5996
Epoch 197/1000, Loss: 0.037511945598655276, Val Loss: 0.03978166729211807, SpearMan: 0.5925
Epoch 198/1000, Loss: 0.03743236553337839, Val Loss: 0.03901539146900177, SpearMan: 0.5952
Epoch 199/1000, Loss: 0.036678718920383185, Val Loss: 0.03968984968960285, SpearMan: 0.5989
Epoch 200/1000, Loss: 0.037101333753930196, Val Loss: 0.03890213258564472, SpearMan: 0.6013
Epoch 201/1000, Loss: 0.03730520926829842, Val Loss: 0.03900292813777924, SpearMan: 0.6053
Epoch 202/1000, Loss: 0.03817697904176182, Val Loss: 0.03900844603776932, SpearMan: 0.6046
Epoch 203/1000, Loss: 0.036819479117790856, Val Loss: 0.03969065807759762, SpearMan: 0.5965
Epoch 204/1000, Loss: 0.03696976995302571, Val Loss: 0.039754771441221234, SpearMan: 0.5908
Epoch 205/1000, Loss: 0.03745342201242844, Val Loss: 0.039293627440929416, SpearMan: 0.5982
Epoch 206/1000, Loss: 0.03686102976401647, Val Loss: 0.039462507143616675, SpearMan: 0.5987
Epoch 207/1000, Loss: 0.037712356386085354, Val Loss: 0.03935715146362782, SpearMan: 0.5983
Epoch 208/1000, Loss: 0.036437255847785205, Val Loss: 0.039141873642802236, SpearMan: 0.5982
Epoch 209/1000, Loss: 0.036440616783996425, Val Loss: 0.03917073607444763, SpearMan: 0.6000
Epoch 210/1000, Loss: 0.0372643583557672, Val Loss: 0.03922945819795132, SpearMan: 0.6069
Epoch 211/1000, Loss: 0.037491607272790536, Val Loss: 0.038351884484291075, SpearMan: 0.6126
Epoch 212/1000, Loss: 0.03786706655389733, Val Loss: 0.038990505412220954, SpearMan: 0.6067
Epoch 213/1000, Loss: 0.03740250815947851, Val Loss: 0.03891579136252403, SpearMan: 0.6021
Epoch 214/1000, Loss: 0.036391599828170404, Val Loss: 0.03883591964840889, SpearMan: 0.6042
Epoch 215/1000, Loss: 0.036686844606366426, Val Loss: 0.039276270940899846, SpearMan: 0.6021
Epoch 216/1000, Loss: 0.03695629919982619, Val Loss: 0.03930511698126793, SpearMan: 0.5997
Epoch 217/1000, Loss: 0.03620184833804766, Val Loss: 0.03959784768521786, SpearMan: 0.5970
Epoch 218/1000, Loss: 0.035807633875972696, Val Loss: 0.03856929764151573, SpearMan: 0.6077
Epoch 219/1000, Loss: 0.03729751788907581, Val Loss: 0.038758724182844165, SpearMan: 0.6053

In [ ]:
def predict(model, test_loader):
  model.eval()
  totalPredictions = []

  with torch.no_grad():
      for X, y in test_loader:
          X = X.to(device)
          predictions = model(X.flatten(start_dim=1))
          totalPredictions.extend(predictions.cpu().numpy().flatten())
  return pd.DataFrame({
          'mutant': df_test['mutant'].values,
          'predicted_score': totalPredictions
      })

In [ ]:
#This cell returns a dict that maps mutants to their 5 fitness scores

model_predicts = [predict(m, test_loader) for m in [model1, model2, model3, model4, model5]]
combined = pd.concat(model_predicts)
mutant_dict = combined.groupby('mutant')['predicted_score'].apply(list).to_dict()
df_test['DMS_score_predicted'] = df_test['mutant'].apply(lambda x: np.mean(mutant_dict[x]))
print(len(mutant_dict))
print(mutant_dict)

11324

In [ ]:
#Find the top 10 based on avg fitness score:

averages = []
for mutation in mutant_dict:
  averages.append((mutation, np.mean(mutant_dict[mutation])))

averages.sort(key=lambda x: x[1], reverse=True)
print(averages[:10])

bestTenList = []
for i in range(10):
  bestTenList.append(averages[i][0])

print(bestTenList)
with open('top10.txt', 'w') as f:
  for mutant in bestTenList:
    f.write(mutant+'\n')

[('P655R', np.float64(0.920874834060669)), ('A654R', np.float64(0.9207105994224548)), ('E653R', np.float64(0.9205482363700866)), ('T652R', np.float64(0.9203854203224182)), ('E651R', np.float64(0.9202219128608704)), ('A649R', np.float64(0.9198930025100708)), ('N648R', np.float64(0.9197275757789611)), ('Q647R', np.float64(0.9195614933967591)), ('T646R', np.float64(0.9193945407867432)), ('P645R', np.float64(0.9192264914512634))]
['P655R', 'A654R', 'E653R', 'T652R', 'E651R', 'A649R', 'N648R', 'Q647R', 'T646R', 'P645R']

In [ ]:
df_pred_model1 = predict(model1, test_loader)
df_test['DMS_score_predicted'] = df_pred_model1['predicted_score']

In [ ]:
# Find top 10 based on model1 predictions
df_pred_model1 = predict(model1, test_loader)

scores = list(zip(df_pred_model1['mutant'], df_pred_model1['predicted_score']))

scores.sort(key=lambda x: x[1], reverse=True)

print(scores[:10])

bestTenList = [mutation for mutation, _ in scores[:10]]

print(bestTenList)

with open('top10.txt', 'w') as f:
    for mutant in bestTenList:
        f.write(mutant + '\n')

[('I569F', 0.9097418785095215), ('Q570F', 0.9097098112106323), ('I568F', 0.9096982479095459), ('P571F', 0.9096742868423462), ('E567F', 0.9096545577049255), ('T572F', 0.9096387028694153), ('R566F', 0.9096109867095947), ('V573F', 0.9096030592918396), ('V574F', 0.9095674753189087), ('G565F', 0.9095672965049744)]
['I569F', 'Q570F', 'I568F', 'P571F', 'E567F', 'T572F', 'R566F', 'V573F', 'V574F', 'G565F']

In [ ]:
#This cell returns a dict that maps mutants to their 5 rankings (based on fitness score)

model_predicts = []
models = [model1, model2, model3, model4, model5]

for i, m in enumerate(models):
    df_pred = predict(m, test_loader)
    df_pred = df_pred.copy()
    df_pred["model_id"] = i
    model_predicts.append(df_pred)

combined = pd.concat(model_predicts, ignore_index=True)

combined["rank"] = combined.groupby("model_id")["predicted_score"].rank(method="average", ascending=False)

rankingDict = (combined.sort_values(["mutant", "model_id"]).groupby("mutant")["rank"].apply(list).to_dict())

print(len(rankingDict))
print(rankingDict)

11324

In [ ]:
df_test[['mutant', 'DMS_score_predicted']].to_csv('predictions.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## 3. Select query for next round

In [ ]:
df_test.sort_values('DMS_score_predicted', ascending=False).head(100)

,mutant,sequence,DMS_score_predicted
11309,P655F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.891732
11287,A654F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.891420
11271,E653F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.891107
11265,T652F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.890793
11231,E651F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.890479
...,...,...,...
9399,Q554F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.852123
9371,L553F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.851659
9364,E552F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.851196
9332,P551F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.850732
9313,A550F,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,0.850267

In [ ]:
trainSet = set(df_train['mutant'])
print(len(trainSet))
print(trainSet)

1340
{'C242K', 'L304S', 'G157V', 'S483P', 'P253K', 'Q484P', 'L308F', 'V331P', 'L88P', 'Y296A', 'I191N', 'R182E', 'R650D', 'G220Y', 'C242D', 'S311A', 'H612D', 'V314N', 'A112Y', 'G254F', 'V314K', 'I258W', 'P276E', 'G254H', 'N295E', 'N289D', 'L309P', 'C242L', 'G157I', 'I255N', 'Y118G', 'L304H', 'R334Y', 'A292G', 'K216C', 'I251N', 'G148Q', 'I224K', 'V302F', 'Y89F', 'G220Q', 'Q508P', 'L335G', 'Y531P', 'H318F', 'R182I', 'L141H', 'P347K', 'F189K', 'D290F', 'F189V', 'L308Q', 'M0N', 'D158I', 'C305E', 'I224C', 'E532P', 'R334D', 'L228G', 'M48K', 'F185L', 'Y89L', 'V314D', 'V302M', 'R182Q', 'K216Q', 'A654H', 'I224V', 'G254I', 'W632H', 'Y320N', 'L228R', 'A221T', 'G297S', 'L304R', 'A292E', 'F319E', 'I255W', 'P315W', 'C242I', 'T463P', 'L335A', 'P253Q', 'Y296I', 'G195M', 'N151I', 'Y296E', 'P276Q', 'R334E', 'I247T', 'G297A', 'R133G', 'A221M', 'P315R', 'R650H', 'L308Y', 'Q227F', 'V193C', 'H126D', 'P315K', 'R182S', 'L304G', 'C305N', 'G297N', 'P253C', 'I298N', 'A112R', 'A221C', 'M48E', 'Y196G', 'P276Y', 'Y505P', 'A221F', 'I496P', 'L228Y', 'K216I', 'I191G', 'A112G', 'G195I', 'I298M', 'V302G', 'A221L', 'T652D', 'D158R', 'G477P', 'L528P', 'V193K', 'N117G', 'Y196N', 'P253W', 'I247F', 'M48H', 'G297L', 'H318K', 'M48D', 'I152L', 'N289M', 'V302W', 'Y320I', 'Y320S', 'G148E', 'G254K', 'N295S', 'H126R', 'V193F', 'N289H', 'F319Q', 'P87R', 'G157R', 'I255H', 'Y89R', 'N151Y', 'T646D', 'I255C', 'K216V', 'L335E', 'L620D', 'I298Y', 'I247L', 'Y320Q', 'I152E', 'F185E', 'L88T', 'C305S', 'L141G', 'G157L', 'L228E', 'M48P', 'L228A', 'I224R', 'A292I', 'P87C', 'G316T', 'G336Y', 'N295M', 'I258Q', 'L533P', 'I481P', 'G336W', 'G297R', 'N648H', 'H318N', 'G148D', 'V618D', 'Y320D', 'P87E', 'G148Y', 'H126E', 'E513P', 'Y196I', 'P645H', 'G195A', 'Y196S', 'V634H', 'G316A', 'N295Q', 'G195T', 'Q526P', 'V252L', 'Y89S', 'H126A', 'Y196T', 'S311V', 'M0D', 'V252N', 'I258A', 'V331R', 'G157Y', 'V193T', 'V634D', 'C305H', 'S311W', 'L641H', 'E122G', 'Y89C', 'L88D', 'L631H', 'I224F', 'V302K', 'N151G', 'V331N', 'G195D', 'I251L', 'I258F', 'Y89H', 'M0I', 'S311C', 'C130G', 'G254C', 'Q227H', 'I224T', 'G254R', 'T128G', 'N629D', 'P347C', 'T516P', 'N151V', 'L88A', 'I191S', 'N488P', 'G316M', 'V193W', 'I191W', 'N289V', 'I258K', 'P315E', 'V635H', 'P315T', 'H318C', 'R182G', 'P250D', 'A460P', 'L88Y', 'G254W', 'R334P', 'P250Q', 'I251H', 'Q476P', 'A292L', 'V331T', 'K530P', 'D158N', 'I247V', 'M127G', 'S492P', 'C630H', 'H126Q', 'I191H', 'A115G', 'I152Y', 'I152S', 'P276C', 'M0H', 'V331W', 'M48R', 'F189T', 'M48S', 'L304Q', 'G157D', 'G195R', 'L642S', 'C242G', 'Y511P', 'V193R', 'L309D', 'Q227K', 'V252F', 'I191T', 'G336V', 'Y196Q', 'N295Y', 'T114G', 'Y196F', 'C305P', 'V252E', 'M0F', 'L304V', 'G220S', 'Y196V', 'M48W', 'V314P', 'P87I', 'V116G', 'G297V', 'D290G', 'P347R', 'G504P', 'L141C', 'P87N', 'R334F', 'A112T', 'I255Q', 'Q227A', 'M48C', 'G336P', 'L228T', 'S464P', 'L304T', 'I152H', 'P250C', 'T520P', 'R475P', 'R182M', 'I258E', 'I255V', 'N295F', 'P87T', 'G157M', 'P347F', 'I191Y', 'P655F', 'A523P', 'G254M', 'L335M', 'Q609D', 'I298E', 'C242V', 'F185W', 'K216S', 'S311M', 'A221N', 'I224Y', 'A221Q', 'L308T', 'Q647H', 'P87F', 'P276V', 'V252C', 'N295K', 'G148M', 'V252G', 'Y296H', 'P347D', 'R334W', 'V193P', 'R182C', 'H318R', 'P253I', 'P276K', 'I251K', 'L88C', 'V252H', 'I251R', 'D158H', 'V252M', 'R182P', 'M0G', 'V314Q', 'F319I', 'K216L', 'G297H', 'C242M', 'L308P', 'F185Q', 'F616D', 'V331G', 'M0P', 'M0S', 'I191M', 'Y320W', 'A292C', 'L88R', 'A521P', 'E651D', 'G148N', 'L304C', 'F185M', 'N295T', 'H126P', 'K509P', 'N289T', 'G503P', 'C305F', 'G336A', 'G316E', 'P250S', 'V621H', 'G336K', 'E653S', 'E468P', 'L141V', 'I224N', 'I258S', 'P87V', 'D290K', 'S493P', 'Y320M', 'L335H', 'D158L', 'L141A', 'A112N', 'G157H', 'F319C', 'I255F', 'I255E', 'S311F', 'F185I', 'A221G', 'G297T', 'H318V', 'V302N', 'N614D', 'K216R', 'L88Q', 'S311T', 'G498P', 'P276N', 'V497P', 'G336S', 'N643S', 'G148H', 'N289E', 'D290A', 'C242P', 'Y89Q', 'F189D', 'P276H', 'I191E', 'Y196W', 'N295G', 'P250N', 'C305A', 'A292H', 'Y320E', 'L335F', 'E135G', 'Y320T', 'I251Y', 'Q227L', 'G220C', 'K216M', 'G195F', 'Y89A', 'V193G', 'I258P', 'P626D', 'A221Y', 'G254S', 'I258H', 'T638H', 'A292Q', 'G157A', 'D290W', 'I152P', 'Q227W', 'V302A', 'L524P', 'V314L', 'C305M', 'L88K', 'F185S', 'N289A', 'A221V', 'S311K', 'N295H', 'I247N', 'I258V', 'R182F', 'A112D', 'P87S', 'K216W', 'F189W', 'G220D', 'P87K', 'Q227G', 'I251T', 'I152R', 'P253D', 'I251G', 'A461P', 'V302C', 'I251E', 'P253S', 'R334A', 'V193M', 'I255S', 'N474P', 'V314S', 'K216N', 'V193L', 'V252Q', 'V302Y', 'N295R', 'V314T', 'G220W', 'Y320R', 'L309A', 'A510P', 'I258T', 'D637H', 'G220F', 'L335I', 'P645S', 'D290V', 'D290Y', 'N151F', 'I224W', 'L309V', 'H318Q', 'L335R', 'I247Q', 'A654D', 'N151C', 'G297W', 'I255K', 'L308S', 'L641D', 'G148R', 'G195N', 'V252D', 'I152D', 'A292P', 'I191L', 'N643D', 'G254T', 'F185A', 'N289I', 'M48L', 'I124G', 'T652H', 'D290M', 'F189H', 'F319T', 'F319V', 'P347Q', 'G316K', 'I224M', 'N648S', 'V193H', 'F189M', 'M0T', 'Y296N', 'P347L', 'Y296Q', 'E640H', 'A292D', 'P315N', 'L617D', 'P87L', 'M48T', 'I255L', 'G336I', 'G489P', 'T123G', 'R182W', 'G195W', 'P250W', 'I258N', 'N289S', 'D158T', 'I152W', 'I258Y', 'V302D', 'G157Q', 'G336R', 'P315H', 'L88G', 'G316H', 'L88N', 'L308N', 'Y296G', 'P276M', 'G220I', 'G336E', 'Y196A', 'L309Q', 'P250A', 'F189N', 'I191F', 'L309E', 'L309C', 'E651H', 'G157E', 'M0R', 'M0E', 'C305T', 'A292V', 'I224L', 'V252W', 'H126V', 'T652S', 'L88F', 'I224A', 'V331Y', 'P655S', 'F185V', 'D158C', 'Y296T', 'L308M', 'R334V', 'L335C', 'F319H', 'L627D', 'H318W', 'P87D', 'L308G', 'M48Q', 'Y320V', 'L304E', 'F185R', 'H318G', 'H126T', 'L304N', 'V302S', 'G316D', 'L88W', 'C242S', 'P347A', 'A112W', 'A654F', 'K216Y', 'G316R', 'H126G', 'C242N', 'A221K', 'C242Q', 'V252R', 'L335Y', 'Y196M', 'G148T', 'I152G', 'P655H', 'V252I', 'P276F', 'I152N', 'S108G', 'L335K', 'D290I', 'N629H', 'P347E', 'K467P', 'G157C', 'R182N', 'Y196D', 'P253G', 'G148F', 'G195L', 'F189C', 'G195P', 'H318P', 'I251D', 'L470P', 'I251A', 'R334T', 'R334N', 'F185G', 'A221I', 'P315G', 'E653H', 'G220E', 'D290Q', 'V302E', 'F515P', 'F185Y', 'Q227N', 'A221R', 'L88M', 'P250E', 'L141M', 'W632D', 'S311H', 'P645D', 'G148S', 'E469P', 'Y296K', 'L304M', 'R650S', 'P276S', 'I298G', 'Y296C', 'T646S', 'G148L', 'P253R', 'M48A', 'S311E', 'P253T', 'R518P', 'V302R', 'D622H', 'L309N', 'E519P', 'D158E', 'L228F', 'I191P', 'G254A', 'G148I', 'Y89N', 'S311L', 'H318D', 'C305W', 'H126K', 'I247E', 'L141F', 'L642H', 'P87Q', 'I298S', 'Q227T', 'G336F', 'N289L', 'D290P', 'I298L', 'P253Y', 'P276D', 'P315I', 'F189A', 'I255P', 'E653D', 'L304F', 'L308C', 'G336T', 'C242R', 'V193Y', 'F189S', 'D158F', 'F319S', 'I251S', 'M48N', 'P253V', 'G157W', 'H126S', 'K216G', 'Q227M', 'G254Q', 'Y89T', 'F507P', 'T646H', 'I191D', 'I298Q', 'C305I', 'L88V', 'D158W', 'L228I', 'I191V', 'C242A', 'N648D', 'N643H', 'M0Y', 'L228V', 'I487P', 'Y615D', 'A649D', 'V314Y', 'A649H', 'F189E', 'M109G', 'Q227V', 'G195C', 'N295W', 'P315M', 'L141W', 'I224G', 'V331H', 'E636H', 'I258R', 'I251V', 'L308D', 'G254V', 'H126M', 'I298A', 'S311I', 'I298T', 'G297E', 'P315V', 'A221E', 'P276I', 'L141K', 'C305R', 'K216F', 'Y610D', 'F319D', 'C242T', 'A112C', 'M0Q', 'G297D', 'L134G', 'C305V', 'I247P', 'I152A', 'P347M', 'F185H', 'H126W', 'L631D', 'L228P', 'I298R', 'R334H', 'G157T', 'N295I', 'A112V', 'L335N', 'K216A', 'A112L', 'I298P', 'D158Y', 'V314I', 'Y296P', 'I255A', 'P347W', 'G157P', 'V193E', 'I152T', 'L304D', 'R182A', 'I247W', 'G254L', 'P87W', 'V331C', 'G297K', 'F189G', 'L308W', 'L304W', 'Y320F', 'P87H', 'P253H', 'I251Q', 'L335V', 'L228W', 'Q633H', 'R182K', 'G195S', 'I251F', 'P250M', 'N295L', 'R334M', 'N295P', 'L308A', 'G148P', 'Y89P', 'D624H', 'G254Y', 'E522P', 'I611D', 'H318E', 'H126L', 'V331I', 'C305Y', 'F625D', 'P250R', 'C305L', 'P276W', 'G316L', 'L479P', 'L121G', 'N486P', 'H318M', 'M48F', 'L141I', 'L309S', 'Y320A', 'C305G', 'L466P', 'R472P', 'V193Q', 'R334C', 'L228K', 'D158S', 'V314M', 'I251C', 'P250F', 'N151R', 'L309W', 'I224D', 'G336D', 'A292N', 'L459P', 'S311N', 'Y196H', 'Y89G', 'G220N', 'I224Q', 'D628H', 'I247S', 'L304A', 'D158A', 'M0W', 'Q227C', 'Y89W', 'Y296L', 'Y89E', 'E462P', 'T652F', 'N289Q', 'F319K', 'Y320P', 'L627H', 'I478P', 'V535P', 'P250I', 'I247H', 'C242F', 'F189P', 'G195Y', 'I607D', 'Y296S', 'R131G', 'F185C', 'C242W', 'A292Y', 'L141P', 'S311Y', 'V331F', 'V331E', 'V193A', 'G316C', 'Y89I', 'D158Q', 'P315L', 'R605D', 'A221H', 'V193S', 'L525P', 'D290N', 'C305D', 'L642D', 'I258G', 'K216D', 'Y320K', 'G316P', 'F319Y', 'S311Q', 'G316V', 'L141Y', 'G195V', 'M0L', 'A112F', 'P250V', 'S311R', 'D158G', 'I191A', 'Y296W', 'Y296R', 'T606D', 'Y196K', 'Q647D', 'E653F', 'F319A', 'G220R', 'F514P', 'P315S', 'A292F', 'I152C', 'R182T', 'Y196E', 'I152M', 'I247G', 'P347I', 'S311G', 'I247C', 'P253E', 'G297C', 'N151M', 'G148W', 'G195Q', 'N151E', 'H126C', 'P347Y', 'I298W', 'M0A', 'P250Y', 'L228S', 'F319N', 'L141D', 'I224E', 'L88H', 'F625H', 'L304K', 'Y89V', 'R644D', 'A112I', 'I298D', 'I224S', 'G336L', 'Q227Y', 'D494P', 'G220A', 'P87A', 'G195K', 'L304P', 'Y89K', 'P253L', 'I255T', 'N151H', 'N289R', 'G195E', 'G220P', 'I255G', 'N151K', 'R182Y', 'F185T', 'Y537P', 'I191R', 'A112S', 'P253M', 'N289C', 'L141T', 'L309Y', 'F189Q', 'I224H', 'V252A', 'V331K', 'L228H', 'F189L', 'V252Y', 'R334K', 'A221W', 'I191K', 'M0K', 'V193I', 'G220T', 'L88E', 'G254P', 'G297Y', 'Y196R', 'F319R', 'P250T', 'V331L', 'P626H', 'F189I', 'R334G', 'I224P', 'A654S', 'N536P', 'N151A', 'F185K', 'D290C', 'N295A', 'N289P', 'I247Y', 'P87Y', 'G336N', 'L335P', 'Y89M', 'I298H', 'G500P', 'Y196C', 'V252K', 'G316S', 'A112H', 'P315Y', 'Y296D', 'V331A', 'I255D', 'I247D', 'G254D', 'M48I', 'F319L', 'A112P', 'T480P', 'R644S', 'K490P', 'N295C', 'Y296F', 'R644H', 'C242E', 'P315Q', 'I298C', 'V302T', 'R534P', 'G195H', 'K216E', 'V302I', 'S311D', 'G148V', 'K216T', 'L309T', 'I608D', 'V331M', 'C129G', 'G316I', 'I255M', 'E640D', 'P347G', 'P347N', 'L335S', 'I247K', 'W499P', 'V314F', 'P276L', 'F319P', 'I191C', 'P253A', 'G157N', 'L335Q', 'G220K', 'I251P', 'L228M', 'E651S', 'L228N', 'L335W', 'I258D', 'K529P', 'F319W', 'L309I', 'G297P', 'S113G', 'L308E', 'V473P', 'L308K', 'R182D', 'P655D', 'N151Q', 'L308H', 'R334I', 'N623H', 'L512P', 'N151L', 'L309H', 'V331S', 'V314R', 'G157F', 'Y320H', 'C305K', 'A221D', 'N289Y', 'L639D', 'D290S', 'D290L', 'I298V', 'N295V', 'H318Y', 'P315C', 'H318I', 'L471P', 'M110G', 'L228D', 'P87M', 'I251W', 'C630D', 'P315F', 'Y320G', 'H318S', 'A292K', 'N151S', 'H318L', 'P347V', 'V314A', 'P253F', 'L308V', 'V331D', 'I111G', 'Y196L', 'R334Q', 'G254N', 'I258C', 'F189Y', 'H318A', 'G336Q', 'L641S', 'S517P', 'A112Q', 'V331Q', 'T638D', 'P276R', 'D290R', 'L309R', 'P315D', 'Q132G', 'I191Q', 'K216P', 'Q227D', 'Q227P', 'G297M', 'L309K', 'I255R', 'P250H', 'L309M', 'P315A', 'F185P', 'R182V', 'G254E', 'V252P', 'L308I', 'N151P', 'G220H', 'A292T', 'G336M', 'Y196P', 'G297I', 'C119G', 'Q227I', 'I247M', 'K216H', 'G316N', 'A112K', 'R182H', 'H318T', 'I152Q', 'C242H', 'E636D', 'N289K', 'I298K', 'A292R', 'N151D', 'A112E', 'L88I', 'P347H', 'F185D', 'Y320L', 'G316Q', 'L228Q', 'V193N', 'D290T', 'M48G', 'N289W', 'I247R', 'F189R', 'H126N', 'P276T', 'D158M', 'L228C', 'A112M', 'P276G', 'I255Y', 'N295D', 'R334S', 'L141N', 'Q227S', 'V506P', 'P250K', 'S311P', 'G297F', 'G336H', 'V302Q', 'L335D', 'V314E', 'Q227E', 'G316F', 'N151W', 'V314C', 'I258L', 'P250L', 'L125G', 'I298F', 'Y296V', 'I258M', 'P87G', 'G220L', 'A649S', 'P250G', 'I251M', 'C305Q', 'H126Y', 'V302H', 'P276A', 'A221S', 'L141R', 'S502P', 'L308R', 'F319M', 'L639H', 'H126I', 'P347T', 'V314H', 'G297Q', 'G157S', 'L304I', 'L88S', 'V527P', 'Q227R', 'N289G', 'D290E', 'Q633D', 'V314G', 'L141Q', 'V314W', 'Y296M', 'L309G', 'V302P', 'I152F', 'A292S', 'P347S', 'A221P', 'R182L', 'I152V', 'R334L', 'L141S', 'N482P', 'D290H', 'N289F', 'G157K', 'V635D', 'M48V', 'A292M', 'M0V', 'A292W', 'L335T', 'F185N', 'V621D', 'N151T', 'L141E', 'N619D', 'G316W', 'Q647S', 'G148A', 'G220V', 'V252S', 'L465P', 'L309F', 'D158K', 'D158P', 'Y320C', 'G148K', 'N623D', 'H126F', 'M48Y', 'C242Y', 'V193D', 'G316Y', 'M0C', 'L304Y', 'I152K', 'D158V', 'F319G', 'Y89D', 'V302L', 'G148C', 'G336C', 'I247A', 'P253N', 'G220M', 'V252T'}

In [ ]:
#SAMPLE BY VARIANCE (QUERY 1)

thompsonArr = []
thompsonQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  var = np.var(currMutationArr, ddof=1)
  thompsonArr.append((mutation, var))

thompsonArr.sort(key=lambda x: x[1], reverse=True)
print(thompsonArr)

currIndex = 0
while len(thompsonQueries) < 100:
  if thompsonArr[currIndex][0] not in trainSet:
    thompsonQueries.append(thompsonArr[currIndex][0])
  currIndex += 1

print(len(thompsonQueries))
print(thompsonQueries)

[('G500P', np.float64(4504707.7)), ('W499P', np.float64(4502442.3)), ('S502P', np.float64(4490730.8)), ('G498P', np.float64(4489664.799999999)), ('V497P', np.float64(4487054.8)), ('G503P', np.float64(4483651.3)), ('G504P', np.float64(4480644.5)), ('Y505P', np.float64(4479951.300000001)), ('I496P', np.float64(4473804.5)), ('V506P', np.float64(4465818.699999999)), ('F507P', np.float64(4455539.3)), ('D494P', np.float64(4450375.199999999)), ('S493P', np.float64(4443956.7)), ('S492P', np.float64(4438410.7)), ('Q508P', np.float64(4437367.3)), ('K490P', np.float64(4429713.800000001)), ('K509P', np.float64(4425582.7)), ('G489P', np.float64(4423014.8)), ('A510P', np.float64(4422589.7)), ('N488P', np.float64(4413891.7)), ('Y511P', np.float64(4411586.2)), ('I487P', np.float64(4406405.7)), ('L512P', np.float64(4399276.3)), ('E513P', np.float64(4392229.5)), ('N486P', np.float64(4380895.7)), ('F514P', np.float64(4367646.3)), ('F515P', np.float64(4353839.699999999)), ('Q484P', np.float64(4347866.2)), ('S483P', np.float64(4320137.8)), ('T516P', np.float64(4319073.5)), ('I478P', np.float64(4314633.2)), ('G477P', np.float64(4302138.199999999)), ('N482P', np.float64(4301349.3)), ('L479P', np.float64(4301203.5)), ('Q476P', np.float64(4286756.7)), ('I481P', np.float64(4285791.2)), ('T480P', np.float64(4277597.3)), ('S517P', np.float64(4271324.2)), ('R475P', np.float64(4270996.3)), ('N474P', np.float64(4248948.7)), ('R518P', np.float64(4239902.7)), ('V473P', np.float64(4218542.8)), ('R472P', np.float64(4197456.2)), ('E519P', np.float64(4194544.300000001)), ('L471P', np.float64(4174052.2)), ('T520P', np.float64(4161471.6999999997)), ('L470P', np.float64(4148182.3)), ('A521P', np.float64(4137916.3)), ('E469P', np.float64(4122275.2)), ('T114G', np.float64(4117555.3)), ('S113G', np.float64(4113990.8)), ('E522P', np.float64(4113650.8)), ('A115G', np.float64(4112659.3)), ('I124G', np.float64(4112069.2000000007)), ('L125G', np.float64(4110393.3)), ('T123G', np.float64(4108435.3000000003)), ('V116G', np.float64(4107363.5)), ('N117G', np.float64(4103907.5)), ('Y118G', np.float64(4099729.3000000003)), ('M127G', np.float64(4097254.1999999997)), ('E468P', np.float64(4094959.7)), ('A523P', np.float64(4094793.6999999997)), ('I111G', np.float64(4094652.5)), ('E122G', np.float64(4094582.2)), ('C119G', np.float64(4092152.8000000003)), ('L121G', np.float64(4085334.6999999997)), ('T128G', np.float64(4085259.6999999997)), ('Q132G', np.float64(4082543.5)), ('L524P', np.float64(4076639.7)), ('C129G', np.float64(4071055.3)), ('K467P', np.float64(4068579.6999999997)), ('C130G', np.float64(4062711.2)), ('L525P', np.float64(4061312.8)), ('R133G', np.float64(4058470.3)), ('R131G', np.float64(4057261.8)), ('Q526P', np.float64(4052476.0)), ('V527P', np.float64(4047106.1999999997)), ('L466P', np.float64(4046230.8)), ('M110G', np.float64(4040823.7)), ('L528P', np.float64(4031733.6999999993)), ('K529P', np.float64(4024297.8000000003)), ('L465P', np.float64(4015925.6999999997)), ('K530P', np.float64(4008859.3000000003)), ('Y531P', np.float64(3996190.0)), ('S464P', np.float64(3992420.3000000003)), ('L134G', np.float64(3977357.0)), ('E532P', np.float64(3974220.8)), ('T463P', np.float64(3969209.3)), ('L533P', np.float64(3953552.3000000003)), ('M109G', np.float64(3948742.1999999997)), ('E462P', np.float64(3937481.3)), ('R534P', np.float64(3918231.7)), ('A461P', np.float64(3910960.6999999993)), ('A460P', np.float64(3888919.3000000003)), ('V535P', np.float64(3887361.7000000007)), ('E135G', np.float64(3879180.2)), ('N536P', np.float64(3859401.3000000007)), ('L459P', np.float64(3859388.2)), ('S108G', np.float64(3853941.0)), ('Y537P', np.float64(3822421.8000000003)), ('E136G', np.float64(3792803.5)), ('E457P', np.float64(3785727.7)), ('H538P', np.float64(3781265.2)), ('S107G', np.float64(3758350.6999999997)), ('D456P', np.float64(3758102.5)), ('L539P', np.float64(3747747.3000000003)), ('N455P', np.float64(3746773.0)), ('W454P', np.float64(3725953.6999999993)), ('V540P', np.float64(3696543.2)), ('L452P', np.float64(3679557.6999999997)), ('N541P', np.float64(3654920.8)), ('C451P', np.float64(3654004.5)), ('T450P', np.float64(3630994.6999999997)), ('T106G', np.float64(3623241.7)), ('V542P', np.float64(3617367.5)), ('I137G', np.float64(3601769.8000000003)), ('V449P', np.float64(3600643.7)), ('H447P', np.float64(3593618.8000000003)), ('K448P', np.float64(3586173.3000000003)), ('G446P', np.float64(3583030.3000000003)), ('R444P', np.float64(3576990.6999999997)), ('K543P', np.float64(3573489.7)), ('N445P', np.float64(3569561.8)), ('N443P', np.float64(3557278.6999999997)), ('G544P', np.float64(3524302.3)), ('E441P', np.float64(3501927.3000000003)), ('E545P', np.float64(3479889.2)), ('G440P', np.float64(3465552.5)), ('N546P', np.float64(3447900.8)), ('E105G', np.float64(3435005.2)), ('S439P', np.float64(3415921.6999999997)), ('I547P', np.float64(3406865.8)), ('L438P', np.float64(3381446.7)), ('T548P', np.float64(3361484.8)), ('Y437P', np.float64(3335080.3000000003)), ('N549P', np.float64(3314357.1999999997)), ('T138G', np.float64(3306510.0)), ('L436P', np.float64(3290358.7)), ('A550P', np.float64(3251958.0)), ('V435P', np.float64(3251466.8000000003)), ('K104G', np.float64(3241452.2)), ('I137P', np.float64(3216488.3)), ('F434P', np.float64(3191895.7)), ('V1L', np.float64(3166308.7)), ('N2L', np.float64(3150099.0)), ('V433P', np.float64(3138456.2)), ('E3L', np.float64(3135168.2)), ('E552P', np.float64(3118429.3000000003)), ('E136P', np.float64(3109138.8000000003)), ('A4L', np.float64(3108988.6999999997)), ('E432P', np.float64(3087910.7)), ('L553P', np.float64(3086355.8000000003)), ('Q554P', np.float64(3056141.3000000003)), ('R5L', np.float64(3052423.7)), ('G6L', np.float64(3028960.6999999997)), ('T138P', np.float64(3024927.8)), ('F431P', np.float64(3020794.0)), ('D103G', np.float64(3007371.2)), ('N7L', np.float64(3003480.8)), ('N556P', np.float64(2994825.6999999997)), ('A461S', np.float64(2985353.6999999997)), ('T463S', np.float64(2983599.7)), ('P458S', np.float64(2978957.5)), ('E462S', np.float64(2977776.8)), ('A460S', np.float64(2974330.8000000007)), ('S8L', np.float64(2974014.0)), ('L459S', np.float64(2972859.6999999997)), ('E457S', np.float64(2968776.1999999997)), ('D456S', np.float64(2966265.8)), ('E468S', np.float64(2966062.7)), ('L466S', np.float64(2961723.2)), ('N455S', np.float64(2961144.7)), ('A557P', np.float64(2959626.7)), ('K467S', np.float64(2958609.8000000003)), ('E469S', np.float64(2956012.3000000003)), ('L465S', np.float64(2954616.8)), ('W454S', np.float64(2949042.3000000003)), ('V430P', np.float64(2947533.5)), ('L470S', np.float64(2947211.0)), ('P453S', np.float64(2940003.6999999997)), ('L452S', np.float64(2934502.0)), ('V558P', np.float64(2930760.2)), ('C451S', np.float64(2918810.7)), ('L471S', np.float64(2918275.2)), ('S9L', np.float64(2915008.7)), ('T559P', np.float64(2907032.7)), ('T450S', np.float64(2906868.7)), ('V621F', np.float64(2897564.2)), ('H612F', np.float64(2895739.1999999997)), ('D613F', np.float64(2892722.3)), ('D622F', np.float64(2892281.1999999997)), ('N619F', np.float64(2892075.1999999997)), ('Y615F', np.float64(2888611.2)), ('N614F', np.float64(2887413.1999999997)), ('V618F', np.float64(2886504.7000000007)), ('L620F', np.float64(2885911.3)), ('V449S', np.float64(2883372.7)), ('N623F', np.float64(2883068.5)), ('Y610F', np.float64(2882893.7000000007)), ('I611F', np.float64(2882522.8)), ('W560P', np.float64(2880360.8000000003)), ('L617F', np.float64(2879147.2999999993)), ('S429P', np.float64(2875649.3)), ('Q609F', np.float64(2875208.5)), ('I608F', np.float64(2872509.7)), ('K448S', np.float64(2869954.1999999997)), ('D624F', np.float64(2866395.2)), ('I607F', np.float64(2866210.3000000003)), ('R605F', np.float64(2860798.3000000003)), ('T606F', np.float64(2859885.3)), ('R472S', np.float64(2856840.2)), ('H447S', np.float64(2847573.2)), ('S604F', np.float64(2846099.5)), ('G561P', np.float64(2844186.5)), ('P626F', np.float64(2838703.1999999993)), ('P603F', np.float64(2835286.7)), ('S602F', np.float64(2831284.3000000003)), ('L627F', np.float64(2829384.8000000003)), ('E601F', np.float64(2823469.3)), ('G446S', np.float64(2822346.5)), ('E428P', np.float64(2817295.5)), ('D628F', np.float64(2811937.6999999997)), ('E600F', np.float64(2811368.5)), ('E599F', np.float64(2806161.2)), ('N445S', np.float64(2800804.6999999997)), ('N629F', np.float64(2798221.3)), ('Y598F', np.float64(2796318.3)), ('V473S', np.float64(2794339.3000000003)), ('L597F', np.float64(2785021.0)), ('E135P', np.float64(2782288.3000000003)), ('K596F', np.float64(2778471.3)), ('C630F', np.float64(2775368.3000000003)), ('R444S', np.float64(2775146.2)), ('G595F', np.float64(2764729.8000000003)), ('E427P', np.float64(2760792.1999999997)), ('I562P', np.float64(2760033.6999999997)), ('M109P', np.float64(2758922.5)), ('N443S', np.float64(2757297.8)), ('N474S', np.float64(2757221.8)), ('S102G', np.float64(2754800.0)), ('L631F', np.float64(2753411.2999999993)), ('W594F', np.float64(2751384.5)), ('R593F', np.float64(2748126.8000000003)), ('W632F', np.float64(2747724.8)), ('T646E', np.float64(2747525.5)), ('P645E', np.float64(2741653.3)), ('N643E', np.float64(2740311.3)), ('E592F', np.float64(2739502.8000000003)), ('R644E', np.float64(2739118.6999999997)), ('Q647E', np.float64(2738887.5)), ('N11L', np.float64(2738102.6999999997)), ('S108P', np.float64(2737800.8)), ('L642E', np.float64(2736242.1999999997)), ('N648E', np.float64(2734897.3000000003)), ('P442S', np.float64(2734060.6999999997)), ('L641E', np.float64(2732881.7)), ('L639E', np.float64(2732774.5)), ('A649E', np.float64(2730162.7)), ('T638E', np.float64(2728475.5)), ('Q633F', np.float64(2727192.8)), ('R650E', np.float64(2724044.0)), ('I591F', np.float64(2722260.2)), ('D637E', np.float64(2721905.5)), ('R475S', np.float64(2720007.3)), ('E441S', np.float64(2716883.1999999997)), ('W590F', np.float64(2716046.3)), ('F563P', np.float64(2707195.3)), ('M110P', np.float64(2706738.5)), ('V634F', np.float64(2705671.7)), ('V635E', np.float64(2703898.5)), ('L589F', np.float64(2702527.8)), ('T652E', np.float64(2695538.6999999997)), ('G440S', np.float64(2694546.0)), ('S426P', np.float64(2693928.8000000003)), ('V634E', np.float64(2691658.7)), ('Q476S', np.float64(2682146.8)), ('Q633E', np.float64(2680448.6999999997)), ('A588F', np.float64(2676005.8)), ('W632E', np.float64(2675191.3000000003)), ('V635F', np.float64(2674781.3000000003)), ('P655E', np.float64(2674576.3)), ('L631E', np.float64(2673902.8000000003)), ('A654E', np.float64(2673025.2)), ('L438S', np.float64(2664760.6999999997)), ('E636F', np.float64(2660823.6999999997)), ('S107P', np.float64(2656557.5)), ('C630E', np.float64(2656250.6999999997)), ('I111P', np.float64(2648850.7)), ('Y437S', np.float64(2647253.5)), ('G477S', np.float64(2643325.8000000003)), ('N629E', np.float64(2641245.7)), ('D637F', np.float64(2640289.7)), ('D628E', np.float64(2639726.6999999997)), ('P12L', np.float64(2636018.8000000003)), ('G120V', np.float64(2635841.5)), ('L121V', np.float64(2635344.0)), ('A586F', np.float64(2632739.7)), ('L627E', np.float64(2632377.6999999997)), ('T425P', np.float64(2631695.3)), ('L436S', np.float64(2625811.7)), ('E585F', np.float64(2625153.6999999993)), ('C119V', np.float64(2622737.3000000003)), ('P626E', np.float64(2619689.8)), ('T638F', np.float64(2619246.8000000003)), ('F625E', np.float64(2613981.6999999997)), ('I478S', np.float64(2612976.5)), ('G565P', np.float64(2610723.6999999997)), ('V435S', np.float64(2604133.5)), ('V540S', np.float64(2603526.2)), ('D584F', np.float64(2602340.0)), ('E122V', np.float64(2601630.7)), ('L639F', np.float64(2599996.5)), ('D624E', np.float64(2598805.2)), ('N623E', np.float64(2598005.5)), ('N536S', np.float64(2597301.8000000003)), ('R566P', np.float64(2597270.7)), ('L539S', np.float64(2592569.3000000003)), ('V535S', np.float64(2591049.2)), ('H538S', np.float64(2590496.8000000003)), ('D622E', np.float64(2590004.3)), ('L533S', np.float64(2588746.3000000003)), ('R534S', np.float64(2588129.1999999997)), ('E640F', np.float64(2587993.8)), ('K583F', np.float64(2587960.3)), ('E567P', np.float64(2586162.7)), ('Y537S', np.float64(2585482.5)), ('L525S', np.float64(2584704.7)), ('E532S', np.float64(2584421.8)), ('K529S', np.float64(2581062.0)), ('Y118V', np.float64(2580978.7)), ('Q526S', np.float64(2580952.3)), ('L641F', np.float64(2579114.8)), ('L528S', np.float64(2578815.3)), ('L524S', np.float64(2577916.3000000003)), ('K530S', np.float64(2577597.7)), ('E519F', np.float64(2576565.2)), ('L479S', np.float64(2576307.8)), ('Y531S', np.float64(2575617.7)), ('A523S', np.float64(2575365.6999999993)), ('V527S', np.float64(2575236.7)), ('V621E', np.float64(2574820.3)), ('R518F', np.float64(2574311.8000000003)), ('I568P', np.float64(2574009.7)), ('S517F', np.float64(2573151.8000000003)), ('L620E', np.float64(2571781.8000000003)), ('F434S', np.float64(2571569.7)), ('W582F', np.float64(2570520.2)), ('L642F', np.float64(2570487.3)), ('E522S', np.float64(2570065.0)), ('T516F', np.float64(2569730.6999999997)), ('H140G', np.float64(2569393.0)), ('V618E', np.float64(2569038.1999999997)), ('L617E', np.float64(2568464.3)), ('T520F', np.float64(2568188.5)), ('N619E', np.float64(2567792.5)), ('N541S', np.float64(2565768.3)), ('F616E', np.float64(2565715.1999999997)), ('L424P', np.float64(2564979.8)), ('T123V', np.float64(2564040.8)), ('A521F', np.float64(2562234.6999999997)), ('T480S', np.float64(2561889.3000000003)), ('A521S', np.float64(2559087.8)), ('T520S', np.float64(2558295.2)), ('I569P', np.float64(2557899.7)), ('N643F', np.float64(2557384.3000000003)), ('Y615E', np.float64(2556606.2)), ('E513F', np.float64(2555819.2)), ('N614E', np.float64(2553632.5)), ('E522F', np.float64(2553514.3)), ('E519S', np.float64(2553381.5)), ('D613E', np.float64(2552346.5)), ('N117V', np.float64(2552281.2)), ('Q570P', np.float64(2551264.5)), ('L512F', np.float64(2550900.2)), ('R644F', np.float64(2550234.7)), ('L134P', np.float64(2549026.6999999997)), ('I481S', np.float64(2548820.3)), ('H612E', np.float64(2548575.6999999997)), ('R518S', np.float64(2547254.6999999997)), ('S113P', np.float64(2545819.0)), ('L512W', np.float64(2544239.8000000003)), ('M580F', np.float64(2543277.7)), ('T516S', np.float64(2542303.6999999997)), ('Y511W', np.float64(2541247.3000000003)), ('F515S', np.float64(2541011.2000000007)), ('A523F', np.float64(2540078.0)), ('E513S', np.float64(2539956.5)), ('N482S', np.float64(2538048.2)), ('Y511F', np.float64(2537423.2)), ('T106P', np.float64(2537354.0)), ('V433S', np.float64(2536994.3000000003)), ('L524F', np.float64(2536167.5)), ('F514S', np.float64(2535980.3000000003)), ('Y511S', np.float64(2535594.3)), ('I611E', np.float64(2535579.7)), ('P645F', np.float64(2535515.6999999997)), ('L512S', np.float64(2535337.3000000003)), ('T572P', np.float64(2534534.1999999997)), ('A510F', np.float64(2531489.7)), ('A510S', np.float64(2529675.3000000003)), ('A510W', np.float64(2527951.3)), ('V542S', np.float64(2527735.0)), ('Y610E', np.float64(2526560.2000000007)), ('Q508S', np.float64(2525444.0)), ('E513W', np.float64(2524488.8)), ('K509W', np.float64(2523831.7)), ('K509F', np.float64(2523747.7)), ('K509S', np.float64(2523718.7)), ('V573P', np.float64(2521604.3000000003)), ('I124V', np.float64(2521563.1999999997)), ('E432S', np.float64(2520592.0)), ('L525F', np.float64(2520491.5)), ('Q609E', np.float64(2520181.6999999997)), ('F507S', np.float64(2518945.3000000003)), ('V506S', np.float64(2516209.8000000003)), ('T646F', np.float64(2515977.5)), ('Q484S', np.float64(2515884.3)), ('Y505S', np.float64(2513731.6999999997)), ('Q508F', np.float64(2512167.1999999997)), ('F514W', np.float64(2511161.0)), ('V574P', np.float64(2510921.3000000003)), ('G504S', np.float64(2510416.7000000007)), ('Q508W', np.float64(2509408.3)), ('I608E', np.float64(2508957.5)), ('P485S', np.float64(2507749.7)), ('Q526F', np.float64(2504681.1999999997)), ('C13L', np.float64(2504274.0)), ('I607E', np.float64(2503961.6999999997)), ('Q647F', np.float64(2501856.5)), ('F507W', np.float64(2501466.8000000003)), ('G503S', np.float64(2500922.8)), ('S578F', np.float64(2498264.3000000003)), ('A115V', np.float64(2498150.3)), ('E423P', np.float64(2498028.8)), ('D575P', np.float64(2497972.0)), ('N486S', np.float64(2496327.3)), ('G500S', np.float64(2495972.6999999997)), ('T606E', np.float64(2493910.3000000003)), ('W499S', np.float64(2492993.3)), ('T114P', np.float64(2492272.7)), ('F431S', np.float64(2491743.6999999997)), ('F515W', np.float64(2491126.3)), ('V430S', np.float64(2489566.8)), ('P501S', np.float64(2488757.3000000003)), ('V506W', np.float64(2486715.8000000003)), ('V527F', np.float64(2486597.5)), ('G498S', np.float64(2484134.3)), ('N648F', np.float64(2483938.3000000003)), ('I487S', np.float64(2483908.6999999997)), ('R605E', np.float64(2482486.6999999997)), ('V577F', np.float64(2478054.7)), ('S604E', np.float64(2477757.2)), ('V497S', np.float64(2477150.2)), ('N488S', np.float64(2476544.8)), ('L528F', np.float64(2476206.0)), ('V577P', np.float64(2475955.3)), ('I496S', np.float64(2475274.7)), ('V506F', np.float64(2474116.7)), ('G489S', np.float64(2473527.5)), ('P495S', np.float64(2472880.5)), ('L125V', np.float64(2472815.5)), ('K543S', np.float64(2472547.8)), ('P603E', np.float64(2471536.8)), ('Y505W', np.float64(2471188.0)), ('T516W', np.float64(2470753.3)), ('D494S', np.float64(2468546.8)), ('K490S', np.float64(2466793.3000000003)), ('A649F', np.float64(2465302.8000000003)), ('S578P', np.float64(2464742.3)), ('K529F', np.float64(2461823.3)), ('E428S', np.float64(2460304.3)), ('T114V', np.float64(2458754.3)), ('S602E', np.float64(2458346.1999999997)), ('P491S', np.float64(2457799.3)), ('P576F', np.float64(2457698.7)), ('G504W', np.float64(2456102.6999999997)), ('Y505F', np.float64(2455274.2)), ('F579P', np.float64(2455258.5)), ('R650F', np.float64(2451360.7)), ('S517W', np.float64(2450477.7)), ('M580P', np.float64(2446187.8)), ('E23M', np.float64(2445813.3)), ('K530F', np.float64(2445372.6999999997)), ('G503W', np.float64(2445051.3000000003)), ('S24M', np.float64(2444139.8)), ('G504F', np.float64(2443557.8000000003)), ('E427S', np.float64(2443403.0)), ('A115P', np.float64(2443243.7)), ('S22M', np.float64(2442759.5)), ('D575F', np.float64(2439744.5)), ('E422P', np.float64(2438077.8)), ('E651F', np.float64(2436876.3)), ('G503F', np.float64(2433984.8)), ('Y531F', np.float64(2433267.6999999997)), ('S502W', np.float64(2433059.0)), ('S113V', np.float64(2432946.8)), ('F581P', np.float64(2432079.3000000003)), ('G21M', np.float64(2431362.7)), ('R518W', np.float64(2428364.3)), ('S25M', np.float64(2424894.7)), ('E532F', np.float64(2424884.3)), ('G544S', np.float64(2424251.5)), ('L533F', np.float64(2422491.3)), ('W582P', np.float64(2422273.3)), ('R534F', np.float64(2422267.3000000003)), ('V535F', np.float64(2421986.3000000003)), ('S502F', np.float64(2421625.7)), ('P501W', np.float64(2420842.0)), ('S20M', np.float64(2420053.2)), ('T652F', np.float64(2419636.8)), ('Y598E', np.float64(2419585.5)), ('G139P', np.float64(2417773.8)), ('V574F', np.float64(2415015.1999999997)), ('P501F', np.float64(2413064.8)), ('Y537F', np.float64(2412985.7)), ('N536F', np.float64(2412866.5)), ('K583P', np.float64(2410005.7)), ('G500W', np.float64(2408014.0)), ('D584P', np.float64(2406704.5)), ('E653F', np.float64(2405101.3000000003)), ('S19M', np.float64(2403666.7)), ('H538F', np.float64(2401392.3000000003)), ('L597E', np.float64(2401101.3)), ('V573F', np.float64(2400434.8)), ('E585P', np.float64(2398572.3)), ('G500F', np.float64(2397378.6999999997)), ('K26M', np.float64(2396581.7)), ('V116P', np.float64(2396328.6999999997)), ('A654F', np.float64(2393227.5)), ('A18M', np.float64(2388114.7)), ('T425S', np.float64(2387861.0)), ('K596E', np.float64(2387843.2)), ('T572F', np.float64(2387292.3)), ('W499F', np.float64(2387274.8000000003)), ('L539F', np.float64(2385094.0)), ('A586P', np.float64(2384271.8)), ('I111V', np.float64(2384072.5)), ('R133P', np.float64(2383423.3)), ('D27M', np.float64(2382501.7)), ('E519W', np.float64(2382049.3000000003)), ('G421P', np.float64(2381067.3)), ('S17M', np.float64(2379

In [ ]:
#SANITY CHECK (Make sure there are none from current test set)

for mutant in thompsonQueries:
  if mutant in trainSet:
    print(mutant)

In [ ]:
with open('query.txt', 'w') as f:
  for mutant in thompsonQueries:
    f.write(mutant+'\n')

In [ ]:
#SAMPLE BY UCB (QUERY 2)

ucbArr = []
ucbQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  std = np.std(currMutationArr, ddof=1)
  mean = np.mean(currMutationArr)
  ucbScore = mean - (4 * std)
  ucbArr.append((mutation, ucbScore))

ucbArr.sort(key=lambda x: x[1])
print(ucbArr)

currIndex = 0
while len(ucbQueries) < 100:
  if ucbArr[currIndex][0] not in trainSet:
    ucbQueries.append(ucbArr[currIndex][0])
  currIndex += 1

print(len(ucbArr))
print(ucbQueries)

[('P655H', np.float64(-7731.72977714244)), ('A654H', np.float64(-7697.82328773932)), ('E653H', np.float64(-7657.191154320303)), ('T652H', np.float64(-7613.359320756201)), ('E651H', np.float64(-7578.296143168789)), ('R650H', np.float64(-7537.311876311471)), ('A649H', np.float64(-7497.523780255446)), ('N648H', np.float64(-7456.377902927291)), ('P655D', np.float64(-7448.242427593406)), ('A654D', np.float64(-7430.068616220439)), ('Q647H', np.float64(-7416.982024343143)), ('E653D', np.float64(-7402.694857243298)), ('T652D', np.float64(-7379.465428405594)), ('T646H', np.float64(-7378.032944433387)), ('E651D', np.float64(-7357.801861196627)), ('P645H', np.float64(-7336.653842144537)), ('R650D', np.float64(-7335.935280661588)), ('A649D', np.float64(-7312.223290452193)), ('R644H', np.float64(-7301.354369565054)), ('N648D', np.float64(-7288.0020542315015)), ('Q647D', np.float64(-7272.426565323264)), ('N643H', np.float64(-7263.11381646566)), ('T646D', np.float64(-7247.947036862015)), ('L642H', np.float64(-7225.474408280092)), ('P645D', np.float64(-7222.393318740727)), ('R644D', np.float64(-7198.345360158405)), ('L641H', np.float64(-7184.440253052733)), ('N643D', np.float64(-7171.691133166832)), ('L642D', np.float64(-7154.176643868452)), ('L641D', np.float64(-7138.82456137216)), ('E640H', np.float64(-7129.89876903536)), ('E640D', np.float64(-7112.351406185603)), ('L639D', np.float64(-7095.68400346949)), ('L639H', np.float64(-7083.176627792227)), ('T638D', np.float64(-7074.399663679466)), ('T638H', np.float64(-7039.569435744998)), ('E636D', np.float64(-7036.304134589312)), ('V635D', np.float64(-7020.563835341015)), ('V634D', np.float64(-6995.707895507667)), ('D637H', np.float64(-6992.784458021676)), ('Q633D', np.float64(-6976.143770877435)), ('W632D', np.float64(-6959.116362961579)), ('E636H', np.float64(-6948.516778583602)), ('L631D', np.float64(-6938.482264343344)), ('C630D', np.float64(-6920.47629880537)), ('V635H', np.float64(-6909.698487855288)), ('N629D', np.float64(-6894.946655226204)), ('V634H', np.float64(-6866.177714125821)), ('L627D', np.float64(-6858.9815531738805)), ('P626D', np.float64(-6835.410115269561)), ('Q633H', np.float64(-6820.785481315564)), ('F625D', np.float64(-6816.718674038704)), ('N623D', np.float64(-6779.077244346058)), ('W632H', np.float64(-6777.9531514281525)), ('L631H', np.float64(-6735.598380037202)), ('V621D', np.float64(-6725.782211284179)), ('L620D', np.float64(-6701.546808724556)), ('C630H', np.float64(-6692.137380064985)), ('P655S', np.float64(-6673.054240673498)), ('N619D', np.float64(-6671.414886998576)), ('N629H', np.float64(-6649.182436445727)), ('A654S', np.float64(-6648.278941350236)), ('V618D', np.float64(-6643.125629199482)), ('E653S', np.float64(-6625.431952908786)), ('L617D', np.float64(-6611.687621521922)), ('D628H', np.float64(-6606.936234048624)), ('T652S', np.float64(-6598.1311470381115)), ('F616D', np.float64(-6586.17182668989)), ('E651S', np.float64(-6565.593277868607)), ('L627H', np.float64(-6565.2157809335295)), ('Y615D', np.float64(-6550.736694270294)), ('R650S', np.float64(-6544.471829300925)), ('N614D', np.float64(-6528.483188863398)), ('P626H', np.float64(-6523.443763927689)), ('A649S', np.float64(-6521.388573794762)), ('N648S', np.float64(-6494.188616477099)), ('H612D', np.float64(-6480.93389925435)), ('F625H', np.float64(-6475.158371604738)), ('Q647S', np.float64(-6461.7472525386875)), ('I611D', np.float64(-6452.387465662028)), ('T646S', np.float64(-6433.602413567869)), ('D624H', np.float64(-6431.500971816825)), ('Y610D', np.float64(-6426.409300682221)), ('P645S', np.float64(-6408.514997180533)), ('Q609D', np.float64(-6400.623210985527)), ('P655F', np.float64(-6388.081656108606)), ('N623H', np.float64(-6387.195643355675)), ('R644S', np.float64(-6380.4851643516995)), ('I608D', np.float64(-6376.833956735809)), ('A654F', np.float64(-6362.576334565312)), ('I607D', np.float64(-6352.640404419901)), ('N643S', np.float64(-6351.60836357313)), ('D622H', np.float64(-6348.514228075386)), ('E653F', np.float64(-6341.901233485711)), ('T606D', np.float64(-6332.507862329479)), ('L642S', np.float64(-6330.711553931373)), ('T652F', np.float64(-6317.486800407119)), ('R605D', np.float64(-6307.464295012569)), ('L641S', np.float64(-6302.964979777296)), ('V621H', np.float64(-6299.941741031454)), ('E651F', np.float64(-6284.3709166218505)), ('S604D', np.float64(-6284.317387825986)), ('E640S', np.float64(-6269.426595817915)), ('P603D', np.float64(-6264.959336303486)), ('L620H', np.float64(-6258.713461616542)), ('R650F', np.float64(-6251.294700659006)), ('L639S', np.float64(-6242.238882381806)), ('S602D', np.float64(-6236.737046584382)), ('A649F', np.float64(-6228.026953127698)), ('N619H', np.float64(-6223.127867882354)), ('N648F', np.float64(-6217.84084742889)), ('E601D', np.float64(-6211.830137702526)), ('T638S', np.float64(-6209.283682070426)), ('Q647F', np.float64(-6193.756936660895)), ('E600D', np.float64(-6193.475876053717)), ('D637S', np.float64(-6184.513062306303)), ('V618H', np.float64(-6174.505980242989)), ('E599D', np.float64(-6164.751877202448)), ('T646F', np.float64(-6164.451909846282)), ('E636S', np.float64(-6153.790805071535)), ('Y598D', np.float64(-6141.749779117368)), ('P645F', np.float64(-6139.342831291216)), ('L617H', np.float64(-6138.51497674036)), ('V635S', np.float64(-6131.231895870189)), ('L597D', np.float64(-6122.326673582343)), ('R644F', np.float64(-6111.594372549782)), ('V634S', np.float64(-6103.000782799258)), ('F616H', np.float64(-6099.440353216698)), ('K596D', np.float64(-6094.751396514469)), ('N643F', np.float64(-6077.629391661518)), ('Q633S', np.float64(-6074.890100615122)), ('G595D', np.float64(-6073.558673638513)), ('Y615H', np.float64(-6059.619010886894)), ('W594D', np.float64(-6049.6389901979355)), ('W632S', np.float64(-6046.056688717687)), ('L642F', np.float64(-6039.580505575649)), ('N614H', np.float64(-6030.279059343303)), ('L631S', np.float64(-6021.77533855075)), ('R593D', np.float64(-6010.447771035293)), ('L641F', np.float64(-6006.442936714885)), ('E592D', np.float64(-5994.512049951203)), ('D613H', np.float64(-5989.818175180736)), ('C630S', np.float64(-5986.431561940957)), ('E640F', np.float64(-5980.170487085452)), ('G35D', np.float64(-5972.196220079372)), ('I591D', np.float64(-5971.909520946056)), ('W590D', np.float64(-5949.662255802953)), ('N629S', np.float64(-5944.724622168151)), ('L639F', np.float64(-5938.53548727496)), ('L589D', np.float64(-5934.1742719180265)), ('I611H', np.float64(-5921.185208540476)), ('D628S', np.float64(-5914.141733687061)), ('T638F', np.float64(-5912.075445267532)), ('A588D', np.float64(-5910.967915018298)), ('P34D', np.float64(-5910.9445033566835)), ('L36D', np.float64(-5904.790243253465)), ('F587D', np.float64(-5896.780661386404)), ('L627S', np.float64(-5882.713836884698)), ('Y610H', np.float64(-5881.96472738901)), ('D637F', np.float64(-5881.7991655968835)), ('A586D', np.float64(-5876.514003627959)), ('E585D', np.float64(-5860.825317002483)), ('P626S', np.float64(-5854.20399489928)), ('E636F', np.float64(-5850.155057974972)), ('Q609H', np.float64(-5844.979379056433)), ('K583D', np.float64(-5830.556014118208)), ('T33D', np.float64(-5824.578778944875)), ('F625S', np.float64(-5820.310309508766)), ('V635F', np.float64(-5814.646008233276)), ('W582D', np.float64(-5811.354701843534)), ('I608H', np.float64(-5807.849745779874)), ('P38D', np.float64(-5801.664236255084)), ('P655E', np.float64(-5794.866500183412)), ('V634F', np.float64(-5790.406918312673)), ('D624S', np.float64(-5785.373262256566)), ('F581D', np.float64(-5784.343025630027)), ('A654E', np.float64(-5776.825551794008)), ('I607H', np.float64(-5775.7040361777235)), ('Q633F', np.float64(-5771.523539795957)), ('M580D', np.float64(-5760.389863084146)), ('N623S', np.float64(-5753.942731318896)), ('T652E', np.float64(-5752.854095915118)), ('T606H', np.float64(-5741.390384717769)), ('W632F', np.float64(-5737.700452134367)), ('F579D', np.float64(-5734.826744442391)), ('D622S', np.float64(-5725.923174232398)), ('R650E', np.float64(-5722.071828335999)), ('L631F', np.float64(-5709.480588954256)), ('S578D', np.float64(-5708.441707830774)), ('A649E', np.float64(-5708.1237703069355)), ('E39D', np.float64(-5705.770847721768)), ('R605H', np.float64(-5703.989482261487)), ('N648E', np.float64(-5694.065062540147)), ('V621S', np.float64(-5693.727878013581)), ('S32D', np.float64(-5688.966895398688)), ('V577D', np.float64(-5686.075122534321)), ('C630F', np.float64(-5680.050481156486)), ('Q647E', np.float64(-5671.905899204133)), ('S604H', np.float64(-5669.403721171417)), ('L620S', np.float64(-5666.4623216884775)), ('T646E', np.float64(-5658.548249559341)), ('P576D', np.float64(-5658.232571339508)), ('C31D', np.float64(-5646.315665185631)), ('N629F', np.float64(-5642.670500539664)), ('N619S', np.float64(-5636.410619844671)), ('P645E', np.float64(-5630.55867066997)), ('P603H', np.float64(-5630.03723330481)), ('V574D', np.float64(-5628.3082848369695)), ('D628F', np.float64(-5616.1228972646095)), ('R644E', np.float64(-5611.794470506816)), ('V573D', np.float64(-5608.737504184478)), ('S602H', np.float64(-5595.004385129576)), ('N643E', np.float64(-5594.614477299781)), ('V618S', np.float64(-5593.436042516063)), ('T572D', np.float64(-5591.417717203698)), ('R40D', np.float64(-5590.613133162649)), ('L627F', np.float64(-5579.9450100293325)), ('L642E', np.float64(-5569.888911318527)), ('P571D', np.float64(-5566.376562135338)), ('E601H', np.float64(-5556.554112973676)), ('L617S', np.float64(-5554.803886970989)), ('P626F', np.float64(-5554.582135415267)), ('Q570D', np.float64(-5549.182946544437)), ('L641E', np.float64(-5533.88545855722)), ('I569D', np.float64(-5527.137396677459)), ('E600H', np.float64(-5525.838819095507)), ('F616S', np.float64(-5519.010617825906)), ('I568D', np.float64(-5511.6503615926)), ('D624F', np.float64(-5505.879947484731)), ('H41D', np.float64(-5500.475801102318)), ('E567D', np.float64(-5490.5390788738505)), ('E599H', np.float64(-5485.986057638043)), ('Y615S', np.float64(-5482.847653841447)), ('N623F', np.float64(-5479.53231759846)), ('L639E', np.float64(-5469.947998895992)), ('R566D', np.float64(-5466.251606061534)), ('R30D', np.float64(-5465.18249627116)), ('N614S', np.float64(-5451.950649444716)), ('G565D', np.float64(-5444.948473124105)), ('T638E', np.float64(-5444.824421595045)), ('Y598H', np.float64(-5442.096259591641)), ('E42D', np.float64(-5440.364497123514)), ('D622F', np.float64(-5438.665570063235)), ('P564D', np.float64(-5428.717251758456)), ('D613S', np.float64(-5417.1805410412)), ('D637E', np.float64(-5413.490032962575)), ('L597H', np.float64(-5407.498697285026)), ('V621F', np.float64(-5405.761190130789)), ('F563D', np.float64(-5400.432621332719)), ('H612S', np.float64(-5385.945807367197)), ('K596H', np.float64(-5371.600007565155)), ('I562D', np.float64(-5369.830744792704)), ('L620F', np.float64(-5365.562873381534)), ('V635E', np.float64(-5359.165768959311)), ('I611S', np.float64(-5355.783536436323)), ('G561D', np.float64(-5343.5232113521415)), ('G595H', np.float64(-5334.867500637189)), ('N619F', np.float64(-5330.348760280553)), ('V634E', np.float64(-5323.375025071516)), ('Y610S', np.float64(-5320.7852544905845)), ('W560D', np.float64(-5319.72541570819)), ('W594H', np.float64(-5309.051074369324)), ('R43D', np.float64(-5305.08572242759)), ('S29D', np.float64(-5297.7874892556265)), ('V618F', np.float64(-5296.190168424318)), ('Q633E', np.float64(-5293.868283052419)), ('T559D', np.float64(-5292.562371173061)), ('Q609S', np.float64(-5290.465788246797)), ('R593H', np.float64(-5274.7852365358885)), ('I608S', np.float64(-5261.183491093486)), ('V558D', np.float64(-5259.657449187756)), ('L617F', np.float64(-5255.501524859589)), ('W632E', np.float64(-5253.207649743895)), ('I607S', np.float64(-5235.27004977044)), ('E592H', np.float64(-5231.378099938973)), ('A557D', np.float64(-5230.120557683688)), ('L631E', np.float64(-5217.346333754884)), ('T606S', np.float64(-5205.377235599371)), ('N556D', np.float64(-5197.067718847626)), ('S28D', np.float64(-5196.618309218893)), ('I591H', np.float64(-5194.637705476975)), ('R605S', np.float64(-5191.658522499675)), ('Y615F', np.float64(-5183.540574472088)), ('C630E', np.float64(-5173.050102860709)), ('P555D', np.float64(-5167.189828637742)), ('W590H', np.float64(-5156.732438015611)), ('N614F', np.float64(-5147.780137322104)), ('P603S', np.float64(-5146.596800550066)), ('N629E', np.float64(-5139.768627772524)), ('Q554D', np.float64(-5136.59857808274)), ('L44D', np.float64(-5126.523577194499)), ('L589H', np.float64(-5118.505321273171)), ('L553D', np.float64(-5109.248298173441)), ('D613F', np.float64(-5109.084485983378)), ('P100W', np.float64(-5105.382970770536)), ('D628E', np.float64(-5103.683656116702)), ('E601S', np.float64(-5094.219126368312)), ('A588H', np.float64(-5082.433561761058)), ('E552D', np.float64(-5078.520997249518)), ('H612F', np.float64(-5075.979771689113)), ('L627E', np.float64(-5068.076253988529)), ('E600S', np.float64(-5062.894998716082)), ('K26D', np.float64(-5061.21075346515)), ('P551D', np.float64(-5044.895372188559)), ('F587H', np.float64(-5044.10669648241)), ('I611F', np.float64(-5036.30349975308)), ('P626E', np.float64(-5029.639790131459)), ('E599S', np.float64(-5024.8473718271025)), ('A550D', np.float64(-5020.292613344485)), ('A586H', np.float64(-5009.545603508618)), ('Y610F', np.float64(-5003.067159302782)), ('F625E', np.float64(-4996.361777512628)), ('D99W', np.float64(-4994.841610048352)), ('Y598S', np.float64(-4993.607518254821)), ('N549D', np.float64(-4984.617136802928)), ('E585H', np.float64(-4972.120200928253)), ('Q609F', np.float64(-4960.2012450754455)), ('L597S', np.float64(-4959.473637467586)), ('D624E', np.float64(-4957.358868510372)), ('R45D', np.float64(-4957.356167920709)), ('T548D', np.float64(-4953.457719519197)), ('S25D', np.float64(-4948.8671090682365)), ('D584H', np.float64(-4935.053390713023)), ('K596S', np.float64(-4927.154632450557)), ('I547D', np.float64(-4922.887161771867)), ('I608F', np.float64(-4919.300506394604)), ('G98W', np.float64(-4918.76941864873)), ('N623E', np.float64(-4911.949853347402)), ('K583H', np.float64(-4905.494895713448)), ('G595S', np.float64(-4899.831212776275)), ('S24D', np.float64(-4897.950741705436)), ('N546D', np.float64(-4893.024758739569)), ('S22D', np.float64(-4885.407666992498)), ('I607F', np.float64(-4883.156890503142)), ('E23D', np.float64(-4879.227689855566)), ('W582H', np.float64(-4878.745125440324)), ('W594S', np.float64(-4872.059503466404)), ('D622E', np.float64(-4871.132099216673)), ('E545D', np.float64(-4857.54969678011)), ('F581H', np.float64(-4841.673582798795)), ('T606F', np.float64(-4838.18732237959)), ('V621E', np.float64(-4829.153685763158)), ('G544D', np.float64(-4824.532101401661)), ('R593S', np.float64(-4823.490172531299)), ('M580H', np.float64(-4811.5288456428425)), ('E46D', np.float64(-4795.717615538568)), ('R605F', np.float64(-4793.041919033767)), ('L620E', np.float64(-4790.947297326564)), ('K543D', np.float64(-4790.898263427405)), ('E592S', np.float64(-4782.405867924287)), ('F579H', np.float64(-4763.7109510381215)), ('V542D', np.float64(-4758.803258386373)), ('N619E', np.float64(-4751.910722166587)), ('S604F', np.float64(-4745.027207760965)), ('I591S', np.float64(-4732.585135954221)), ('N541D', np.float64(-4727.00330872926)), ('S578H', np.float64(-4711.848540569331)), ('P603F', np.float64(-4709.617779427923)), ('V618E', np.float64(-4708.512654533917)), ('V540D', np.float64(-4694.048827912976)), ('W590S', np.float64(-4690.728748166536)), ('G21D', np.float64(-4674.755441687878)), ('S602F', np.float64(-4664.044183241665)), ('L617E', np.float64(-4660.945547747518)), ('L539D', np.float64(-4660.758650165847)), ('V577H', np.float64(-4653.581587002125)), ('L589S', np.float64(-4635.202103715698)), ('E601F', np.float64(-4631.36604763185)), ('H538D', np.float64(-4628.377403245221)), ('F616E', np.float64(-4620.320355502288)), ('P576H', np.float64(-4606.858609429713)), ('K47D', np.float64(-4606.280867397581)), ('Y537D', np.float64(-4591.012592162212)), ('A588S', np.float64(-4587.121341767495)), ('Y615E', np.float64(-4583.922051590275)), ('E600F', np.float64(-4579.51124116665)), ('P655K', np.float64(-4561.534109708555)), ('D575H', np.float64(-4553.903223989836)), ('N614E', np.float64(-4549.695380535078)), ('N536D', np.float64(-4547.909365973637)), ('E599F', np.float64(-4542.983385347508)), ('F587S', np.float64(-4542.03201317259)), ('A654K', np.float64(-4537.5724019883655)), ('E653K', np.float64(-4516.710147957539)), ('V535D', np.float64(-4510.473351691449)), ('V574H', np.float64(-4508.066050040853)), ('D613E', np.float64(-4504.1788518094145)), ('A586S', np.float64(-4502.139642563035)), ('T652K', np.float64(-4501.813633807382)), ('Y598F', np.float64(-4489.98079223153)), ('A97W', np.float64(-4480.411513742994)), ('E651K', np.float64(-4475.835839829677)), ('R534D', np.float64(-4471.485505105974)), ('V573H', np.float64(-4466.955674883457)), ('R650K', np.float64(-4466.566410869214)), ('L416P', np.float64(-4461.282044482984)), ('E585S', np.float64(-4456.037242406305)), ('H612E', np.float64(-4456.026590152044)), ('L597F', np.float64(-4448.048679198337)), ('A649K', np.float64(-4447.586159196297)), ('S20D', np.float64(-4442.005701544073)), ('L533D', np.float64(-4439.847703752543)), ('T572H', np.float64(-4437.949687542363)), ('N648K', np.float64(-4423.829001062743)), ('I611E', np.float64(-4413.388675283625)), ('D584S', np.float64(-4408.994184169813)), ('P571H', np.float64(-4407.619468010392)), ('E532D', np.float64(-4406.612122792774)), ('K596F', np.float64(-4402.403715061017)), ('E415P', np.float64(-4400.315289809561)), ('Q647K', np.float64(-4394.972988963372)), ('Y531D', np.float64(-4379.010598683228)), ('Q570H', np.float64(-4378.508249782455)), ('Y610E', np.float64(-4372.003830771504)), ('T646K', np.float64(-4369.936347110969)), ('K583S', np.float64(-4362.365365874849)), ('G595F', np.float64(-4357.223687070914)), ('P645K', np.float64(-4353.6266689959475)), ('K530D', np.float64(-4346.258211171627)), ('I569H', np.float64(-4342.885212949395)), ('K413P', np.float64(-4341.535557257908)), ('R644K', np.float64(-4337.299176540676)), ('E414P', np.float64(-4331.699576874723)), ('Q609E', np.float64(-4328.432439722134)), ('N643K', np.float64(-4321.084093974898)), ('K529D', np.float64(-4320.010034595427)), ('L417P', np.float64(-4317.852417853174)), ('W582S', np.float64(-4311.989712005448)), ('G101W', np.float64(-4311.726933311583)), ('I568H', np.float64(-4311.231382024491)), ('W594F', np.float64(-4308.901022545557)), ('L528D', np.float64(-4292.083925836275)), ('I608E', np.float64(-4290.245730532386)), ('R49D', np.float64(-4289.153396221907)), ('L642K', np.float64(-4279.154933644556)), ('S411P', np.float64(-4277.472930223808)), ('K410P', np.float64(-4272.66330994272)), ('E567H', np.float64(-4270.483850902685)), ('S409P', np.float64(-4270.302198082594)), ('F581S', np.float64(-4270.05273286361)), ('A144G', np.float64(-4269.128905480782)), ('R593F', np.float64(-4268.258357284702)), ('V527D', np.float64(-4262.551233591259)), ('L641K', np.float64(-4253.998531663652)), ('I607E', np.float64(-4248.930647034633)), ('Q526D', np.float64(-4240.254941351052)), ('R566H', np.float64(-4236.236323806356)), ('E640K', np.float64(-4231.192174850234)), ('N74L', np.float64(-4227.351637763832)), ('L525D', np.float64(-4219.234769690573)), ('M580S', np.float64(-4216.627532816989)), ('E592F', np.float64(-4216.158074588288)), ('K143G', np.float64(-4212.576794906772)), ('G86P', np.float64(-4211.561499569856)), ('L639K', np.float64(-4205.759908213172)), ('T606E', np.float64(-4205.013552040871)), ('G565H', np.float64(-4200.823374900783)), ('L524D', np.float64(-4191.81907348714)), ('T638K', np.float64(-4189.683785048752)), ('I591F', np.float64(-4171.251798491866)), ('F579S', np.float64(-4169.500223307328)), ('A523D', np.float64(-4165.25718841657)), ('P564H', np.float64(-4163.371837395068)), ('D637K', np.float64(-4163.359673734139)), ('R605E', np.float64(-4157.962201763326)), ('V73L', np.float64(-4155.195404300048)), ('K418P

In [ ]:
#SANITY CHECK (Make sure there are none from current test set)

for mutant in ucbQueries:
  if mutant in trainSet:
    print(mutant)

In [ ]:
with open('query.txt', 'w') as f:
  for mutant in ucbQueries:
    f.write(mutant+'\n')

In [ ]:
#GREEDY SAMPLING (QUERY 3)

greedyArr = []
greedyQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  mean = np.mean(currMutationArr)
  greedyArr.append((mutation, mean))

greedyArr.sort(key=lambda x: x[1])
print(greedyArr)

currIndex = 0
while len(greedyQueries) < 100:
  if greedyArr[currIndex][0] not in trainSet:
    greedyQueries.append(greedyArr[currIndex][0])
  currIndex += 1
print(len(greedyQueries))
print(greedyQueries)

[('P655F', np.float64(37.0)), ('A654F', np.float64(38.4)), ('E653F', np.float64(40.2)), ('T652F', np.float64(41.4)), ('E651F', np.float64(43.2)), ('R650F', np.float64(44.6)), ('A649F', np.float64(46.4)), ('N648F', np.float64(47.6)), ('Q647F', np.float64(49.2)), ('T646F', np.float64(51.0)), ('P645F', np.float64(52.6)), ('R644F', np.float64(53.8)), ('N643F', np.float64(55.6)), ('L642F', np.float64(57.2)), ('L641F', np.float64(58.8)), ('E640F', np.float64(60.0)), ('L639F', np.float64(62.0)), ('T638F', np.float64(63.4)), ('D637F', np.float64(65.0)), ('E636F', np.float64(66.4)), ('V635F', np.float64(68.0)), ('V634F', np.float64(69.6)), ('Q633F', np.float64(70.8)), ('W632F', np.float64(72.8)), ('L631F', np.float64(74.0)), ('C630F', np.float64(75.6)), ('N629F', np.float64(77.0)), ('D628F', np.float64(78.6)), ('L627F', np.float64(80.0)), ('P626F', np.float64(81.4)), ('D624F', np.float64(83.6)), ('N623F', np.float64(85.0)), ('D622F', np.float64(86.4)), ('V621F', np.float64(88.0)), ('L620F', np.float64(89.4)), ('N619F', np.float64(90.8)), ('V618F', np.float64(92.6)), ('L617F', np.float64(94.2)), ('Y615F', np.float64(96.2)), ('N614F', np.float64(97.4)), ('D613F', np.float64(99.0)), ('H612F', np.float64(100.4)), ('I611F', np.float64(102.0)), ('Y610F', np.float64(103.4)), ('Q609F', np.float64(105.2)), ('I608F', np.float64(106.6)), ('I607F', np.float64(108.0)), ('T606F', np.float64(109.4)), ('R605F', np.float64(110.8)), ('S604F', np.float64(112.4)), ('P603F', np.float64(113.8)), ('S602F', np.float64(115.4)), ('E601F', np.float64(116.6)), ('E600F', np.float64(118.2)), ('E599F', np.float64(119.8)), ('Y598F', np.float64(121.4)), ('L597F', np.float64(122.4)), ('K596F', np.float64(124.0)), ('G595F', np.float64(125.6)), ('W594F', np.float64(126.8)), ('R593F', np.float64(128.6)), ('E592F', np.float64(130.2)), ('I591F', np.float64(131.2)), ('W590F', np.float64(132.8)), ('L589F', np.float64(134.6)), ('A588F', np.float64(135.8)), ('A586F', np.float64(138.0)), ('E585F', np.float64(139.2)), ('D584F', np.float64(140.8)), ('K583F', np.float64(142.4)), ('W582F', np.float64(144.2)), ('M580F', np.float64(145.8)), ('S578F', np.float64(148.0)), ('V577F', np.float64(149.6)), ('P576F', np.float64(151.4)), ('D575F', np.float64(152.6)), ('V574F', np.float64(154.6)), ('V573F', np.float64(156.4)), ('T572F', np.float64(158.0)), ('P571F', np.float64(159.4)), ('Q570F', np.float64(161.2)), ('I569F', np.float64(163.2)), ('I568F', np.float64(164.8)), ('E567F', np.float64(166.4)), ('R566F', np.float64(168.4)), ('G565F', np.float64(170.4)), ('P564F', np.float64(172.0)), ('I562F', np.float64(174.4)), ('G561F', np.float64(176.4)), ('W560F', np.float64(178.4)), ('T559F', np.float64(180.0)), ('V558F', np.float64(181.8)), ('A557F', np.float64(183.4)), ('N556F', np.float64(185.4)), ('P555F', np.float64(187.2)), ('Q554F', np.float64(189.0)), ('L553F', np.float64(190.6)), ('E552F', np.float64(192.6)), ('P551F', np.float64(194.2)), ('A550F', np.float64(196.2)), ('N549F', np.float64(198.0)), ('T548F', np.float64(199.8)), ('I547F', np.float64(202.2)), ('N546F', np.float64(203.6)), ('E545F', np.float64(206.2)), ('G544F', np.float64(209.4)), ('K543F', np.float64(212.2)), ('V542F', np.float64(214.0)), ('N541F', np.float64(216.6)), ('V540F', np.float64(219.2)), ('L539F', np.float64(221.4)), ('H538F', np.float64(223.2)), ('Y537F', np.float64(225.8)), ('N536F', np.float64(227.8)), ('V535F', np.float64(230.6)), ('R534F', np.float64(232.0)), ('L533F', np.float64(235.0)), ('E532F', np.float64(237.8)), ('Y531F', np.float64(239.6)), ('K530F', np.float64(242.4)), ('K529F', np.float64(244.6)), ('L528F', np.float64(247.4)), ('V527F', np.float64(249.6)), ('Q526F', np.float64(251.6)), ('L525F', np.float64(254.0)), ('L524F', np.float64(257.0)), ('A523F', np.float64(259.4)), ('E522F', np.float64(261.8)), ('A521F', np.float64(264.6)), ('T520F', np.float64(268.2)), ('E519F', np.float64(271.2)), ('R518F', np.float64(275.0)), ('S517F', np.float64(278.6)), ('T516F', np.float64(282.4)), ('P655S', np.float64(283.8)), ('A654S', np.float64(286.4)), ('E653S', np.float64(289.2)), ('T652S', np.float64(291.2)), ('E513F', np.float64(292.4)), ('E651S', np.float64(294.8)), ('R650S', np.float64(296.8)), ('L512F', np.float64(297.0)), ('A649S', np.float64(300.0)), ('Y511F', np.float64(300.8)), ('N648S', np.float64(302.4)), ('A510F', np.float64(305.4)), ('Q647S', np.float64(305.4)), ('T646S', np.float64(307.6)), ('K509F', np.float64(309.8)), ('P645S', np.float64(310.4)), ('R644S', np.float64(313.2)), ('Q508F', np.float64(314.4)), ('N643S', np.float64(316.0)), ('L642S', np.float64(318.6)), ('L641S', np.float64(322.2)), ('V506F', np.float64(325.0)), ('E640S', np.float64(325.6)), ('L639S', np.float64(328.4)), ('Y505F', np.float64(331.2)), ('T638S', np.float64(332.2)), ('D637S', np.float64(335.6)), ('G504F', np.float64(338.0)), ('E636S', np.float64(338.2)), ('V635S', np.float64(341.2)), ('G503F', np.float64(344.0)), ('V634S', np.float64(344.4)), ('Q633S', np.float64(348.6)), ('S502F', np.float64(350.8)), ('W632S', np.float64(351.2)), ('L631S', np.float64(354.4)), ('P501F', np.float64(356.4)), ('C630S', np.float64(357.8)), ('N629S', np.float64(360.2)), ('G500F', np.float64(363.0)), ('D628S', np.float64(363.6)), ('L627S', np.float64(367.0)), ('W499F', np.float64(369.0)), ('P626S', np.float64(370.2)), ('F625S', np.float64(373.6)), ('G498F', np.float64(375.6)), ('D624S', np.float64(377.2)), ('N623S', np.float64(380.4)), ('V497F', np.float64(382.8)), ('D622S', np.float64(385.0)), ('I496F', np.float64(388.8)), ('V621S', np.float64(388.8)), ('L620S', np.float64(392.2)), ('P495F', np.float64(396.0)), ('N619S', np.float64(396.4)), ('V618S', np.float64(400.4)), ('D494F', np.float64(402.2)), ('L617S', np.float64(404.0)), ('F616S', np.float64(407.6)), ('S493F', np.float64(410.4)), ('Y615S', np.float64(410.6)), ('N614S', np.float64(414.4)), ('S492F', np.float64(417.4)), ('D613S', np.float64(418.2)), ('H612S', np.float64(421.8)), ('P491F', np.float64(425.0)), ('I611S', np.float64(425.4)), ('Y610S', np.float64(428.8)), ('K490F', np.float64(433.6)), ('Q609S', np.float64(433.6)), ('I608S', np.float64(436.8)), ('I607S', np.float64(440.0)), ('G489F', np.float64(440.4)), ('T606S', np.float64(443.6)), ('N488F', np.float64(447.6)), ('R605S', np.float64(448.0)), ('P603S', np.float64(454.6)), ('I487F', np.float64(455.2)), ('P655W', np.float64(459.8)), ('E601S', np.float64(460.4)), ('N486F', np.float64(462.4)), ('E600S', np.float64(464.6)), ('A654W', np.float64(465.8)), ('E599S', np.float64(467.2)), ('P485F', np.float64(470.0)), ('Y598S', np.float64(471.0)), ('E653W', np.float64(471.2)), ('L597S', np.float64(475.6)), ('T652W', np.float64(477.2)), ('Q484F', np.float64(477.6)), ('K596S', np.float64(478.6)), ('E651W', np.float64(482.4)), ('G595S', np.float64(482.4)), ('S483F', np.float64(485.4)), ('W594S', np.float64(487.2)), ('R650W', np.float64(488.8)), ('R593S', np.float64(490.2)), ('N482F', np.float64(492.8)), ('A649W', np.float64(494.2)), ('E592S', np.float64(495.0)), ('I591S', np.float64(498.2)), ('I481F', np.float64(500.0)), ('N648W', np.float64(500.4)), ('W590S', np.float64(501.4)), ('L589S', np.float64(506.2)), ('Q647W', np.float64(506.4)), ('T480F', np.float64(508.4)), ('A588S', np.float64(509.6)), ('T646W', np.float64(511.8)), ('F587S', np.float64(513.0)), ('L479F', np.float64(516.2)), ('P645W', np.float64(518.0)), ('A586S', np.float64(518.8)), ('E585S', np.float64(522.2)), ('R644W', np.float64(523.2)), ('I478F', np.float64(525.2)), ('D584S', np.float64(525.6)), ('N643W', np.float64(529.4)), ('K583S', np.float64(530.8)), ('G477F', np.float64(534.8)), ('W582S', np.float64(535.0)), ('L642W', np.float64(535.2)), ('F581S', np.float64(539.2)), ('L641W', np.float64(542.2)), ('M580S', np.float64(543.6)), ('Q476F', np.float64(543.6)), ('F579S', np.float64(547.6)), ('E640W', np.float64(548.6)), ('L639W', np.float64(553.4)), ('R475F', np.float64(553.6)), ('V577S', np.float64(555.2)), ('P576S', np.float64(558.6)), ('T638W', np.float64(560.0)), ('D575S', np.float64(562.8)), ('N474F', np.float64(563.0)), ('D637W', np.float64(566.0)), ('V574S', np.float64(567.6)), ('V473F', np.float64(572.0)), ('V573S', np.float64(572.0)), ('E636W', np.float64(573.2)), ('T572S', np.float64(576.0)), ('V635W', np.float64(579.0)), ('P571S', np.float64(581.2)), ('P655L', np.float64(582.2)), ('R472F', np.float64(582.8)), ('Q570S', np.float64(584.6)), ('A654L', np.float64(585.4)), ('V634W', np.float64(586.4)), ('E653L', np.float64(588.6)), ('I569S', np.float64(588.8)), ('T652L', np.float64(592.2)), ('L471F', np.float64(592.8)), ('I568S', np.float64(593.6)), ('Q633W', np.float64(594.2)), ('E651L', np.float64(596.4)), ('E567S', np.float64(598.0)), ('R650L', np.float64(601.6)), ('R566S', np.float64(601.8)), ('L470F', np.float64(603.0)), ('A649L', np.float64(605.8)), ('G565S', np.float64(606.6)), ('L631W', np.float64(608.6)), ('N648L', np.float64(610.4)), ('P564S', np.float64(610.6)), ('E469F', np.float64(612.2)), ('Q647L', np.float64(614.2)), ('C630W', np.float64(615.4)), ('F563S', np.float64(615.6)), ('T646L', np.float64(618.6)), ('I562S', np.float64(619.8)), ('E468F', np.float64(622.8)), ('N629W', np.float64(623.8)), ('P645L', np.float64(623.8)), ('G561S', np.float64(625.2)), ('R644L', np.float64(628.4)), ('W560S', np.float64(630.4)), ('D628W', np.float64(632.6)), ('K467F', np.float64(632.8)), ('N643L', np.float64(633.2)), ('T559S', np.float64(634.4)), ('V558S', np.float64(639.6)), ('L627W', np.float64(639.8)), ('L466F', np.float64(642.8)), ('E640L', np.float64(643.6)), ('A557S', np.float64(643.8)), ('F59W', np.float64(645.0)), ('S60W', np.float64(645.0)), ('E62W', np.float64(645.4)), ('L61W', np.float64(645.6)), ('F63W', np.float64(645.8)), ('F64W', np.float64(646.8)), ('K57W', np.float64(646.8)), ('P65W', np.float64(647.2)), ('D56W', np.float64(647.8)), ('P626W', np.float64(647.8)), ('N556S', np.float64(649.2)), ('P66W', np.float64(649.4)), ('G55W', np.float64(651.0)), ('R67W', np.float64(651.0)), ('T638L', np.float64(652.0)), ('L465F', np.float64(652.2)), ('S54W', np.float64(653.0)), ('T68W', np.float64(653.0)), ('P555S', np.float64(653.8)), ('A69W', np.float64(655.2)), ('E53W', np.float64(655.6)), ('F625W', np.float64(656.2)), ('D637L', np.float64(656.4)), ('L52W', np.float64(657.4)), ('E70W', np.float64(659.0)), ('Q554S', np.float64(659.0)), ('R51W', np.float64(659.0)), ('E636L', np.float64(660.6)), ('S464F', np.float64(662.2)), ('R50W', np.float64(662.6)), ('G71W', np.float64(662.8)), ('L553S', np.float64(664.0)), ('R49W', np.float64(664.4)), ('D624W', np.float64(664.8)), ('V635L', np.float64(665.6)), ('A72W', np.float64(666.4)), ('E552S', np.float64(668.4)), ('K47W', np.float64(669.2)), ('V634L', np.float64(669.6)), ('V73W', np.float64(671.2)), ('Q633L', np.float64(673.0)), ('T463F', np.float64(673.0)), ('E46W', np.float64(673.2)), ('P551S', np.float64(673.4)), ('N623W', np.float64(673.6)), ('N74W', np.float64(676.6)), ('W632L', np.float64(677.2)), ('R45W', np.float64(678.4)), ('A550S', np.float64(678.6)), ('D622W', np.float64(682.2)), ('L75W', np.float64(682.4)), ('E462F', np.float64(683.0)), ('L44W', np.float64(683.2)), ('C630L', np.float64(684.2)), ('N549S', np.float64(684.2)), ('R43W', np.float64(688.0)), ('T548S', np.float64(688.4)), ('I76W', np.float64(688.8)), ('N629L', np.float64(689.0)), ('V621W', np.float64(691.0)), ('E42W', np.float64(692.0)), ('D628L', np.float64(693.4)), ('I547S', np.float64(693.4)), ('A461F', np.float64(693.8)), ('S77W', np.float64(696.6)), ('N546S', np.float64(698.2)), ('H41W', np.float64(699.2)), ('L620W', np.float64(702.6)), ('A460F', np.float64(703.8)), ('P626L', np.float64(704.2)), ('E545S', np.float64(704.4)), ('R78W', np.float64(706.6)), ('G544S', np.float64(708.4)), ('R40W', np.float64(708.6)), ('F625L', np.float64(710.4)), ('N619W', np.float64(711.6)), ('K543S', np.float64(714.2)), ('L459F', np.float64(714.6)), ('E39W', np.float64(715.0)), ('D624L', np.float64(716.6)), ('V542S', np.float64(718.8)), ('V618W', np.float64(718.8)), ('N623L', np.float64(722.4)), ('P38W', np.float64(723.2)), ('N541S', np.float64(724.2)), ('P458F', np.float64(725.0)), ('F79W', np.float64(725.4)), ('L617W', np.float64(728.1)), ('D622L', np.float64(728.4)), ('V540S', np.float64(730.4)), ('D37W', np.float64(731.8)), ('E457F', np.float64(734.8)), ('V621L', np.float64(735.2)), ('F616W', np.float64(735.6)), ('L539S', np.float64(735.8)), ('W58F', np.float64(736.6)), ('K57F', np.float64(738.6)), ('D56F', np.float64(739.0)), ('S60F', np.float64(740.2)), ('L36W', np.float64(741.0)), ('H538S', np.float64(741.8)), ('L61F', np.float64(741.8)), ('G55F', np.float64(742.4)), ('E62F', np.float64(743.8)), ('Y615W', np.float64(743.8)), ('D456F', np.float64(746.0)), ('N619L', np.float64(746.4)), ('S54F', np.float64(746.4)), ('Y537S', np.float64(747.4)), ('P655R', np.float64(749.4)), ('G35W', np.float64(750.6)), ('N614W', np.float64(751.8)), ('V618L', np.float64(752.4)), ('N536S', np.float64(753.6)), ('E53F', np.float64(754.0)), ('P65F', np.float64(754.2)), ('A654R', np.float64(755.6)), ('D80W', np.float64(755.8)), ('N455F', np.float64(757.4)), ('V535S', np.float64(758.4)), ('D613W', np.float64(760.0)), ('P34W', np.float64(760.8)), ('P66F', np.float64(760.8)), ('E653R', np.float64(761.6)), ('F616L', np.float64(762.8)), ('L52F', np.float64(763.4)), ('P655I', np.float64(764.2)), ('R534S', np.float64(764.4)), ('R67F', np.float64(766.2)), ('H612W', np.float64(767.8)), ('T652R', np.float64(768.2)), ('W454F', np.float64(769.0)), ('Y615L', np.float64(770.0)), ('L533S', np.float64(770.4)), ('A654I', np.float64(771.0)), ('T68F', np.float64(771.0)), ('T33W', np.float64(775.0)), ('I611W', np.float64(775.4)), ('E532S', np.float64(775.6)), ('N614L', np.float64(775.8)), ('A69F', np.float64(776.6)), ('E651R', np.float64(777.2)), ('E653I', np.float64(778.2)), ('R51F', np.float64(780.0)), ('P453F', np.float64(781.0)), ('E70F', np.float64(781.8)), ('D613L', np.float64(782.4)), ('Y531S', np.float64(782.4)), ('Y610W', np.float64(784.0)), ('T652I', np.float64(785.2)), ('K530S', np.float64(788.4)), ('H612L', np.float64(788.6)), ('G71F', np.float64(789.0)), ('E651I', np.float64(791.4)), ('L452F', np.float64(792.4)), ('Q609W', np.float64(792.6)), ('R50F', np.float64(793.6)), ('I611L', np.float64(795.0)), ('A649R', np.float64(795.2)), ('S32W', np.float64(795.4)), ('K529S', np.float64(795.6)), ('A72F', np.float64(797.2)), ('R650I', np.float64(798.8)), ('I608W', np.float64(799.4)), ('R81W', np.float64(801.2)), ('L528S', np.float64(801.4)), ('Y610L', np.float64(802.4)), ('V73F', np.float64(802.8)), ('N648R', np.float64(803.6)), ('A649I', np.float64(804.6)), ('R49F', np.float64(804.8)), ('C451F', np.float64(805.6)), ('V527S', np.float64(807.8)), ('I607W', np.float64(808.0)), ('N74F', np.float64(808.2)), ('Q609L', np.float64(809.8)), ('N648I', np.float64(810.4)), ('Q647R', np.float64(810.8)), ('L75F', np.float64(814.4)), ('Q526S', np.float64(815.2)), ('T606W', np.float64(815.6)), ('C31W', np.float64(816.4)), ('I608L', np.float64(816.4)), ('Q647I', np.float64(817.6)), ('T646R', np.float64(818.4)), ('I76F', np.float64(821.0)), ('L525S', np.float64(822.4)), ('I607L', np.float64(824.0)), ('T646I', np.float64(824.2)), ('R605W', np.float64(825.0)), ('T450F', np.float64(825.0)), ('P645R', np.float64(825.2)), ('S77F', np.float64(829.2)), ('L524S', np.float64(829.4)), ('T606L', np.float64(830.0)), ('P645I', np.float64(831.2)), ('K47F', np.float64(831.4)), ('S604W', np.float64(834.0)), ('A523S', np.float64(836.0)), ('R605L', np.float64(837.6)), ('R644I', np.float64(837.8)), ('R78F', np.float64(838.2)), ('N643R', np.float64(839.8)), ('V449F', np.float64(842.4)), ('P603W', np.float64(842.8)), ('N643I', np.float64(844.0)), ('E522S', np.float64(845.0)), ('R30W', np.float64(845.8)), ('S604L', np.float64(846.4)), ('L642R', np.float64(846.8)), ('E46F', np.float64(849.2)), ('S602W', np.float64(850.0)), ('L642I', np.float64(850.6)), ('A654P', np.float64(852.0)), ('A521S', np.float64(852.2)), ('P603L', np.float64(853.0)), ('L641R', np.float64(854.6)), ('L641I', np.float64(857.0)), ('K448F', np.float64(859.6)), ('T520S', np.float64(859.6)), ('E601W', np.float64(859.8)), ('E653P', np.float64(861.0)), ('D80F', np.float64(861.2)), ('E640R', np.float64(861.2)), ('S602L', np.float64(861.2)), ('E640I', np.float64(862.8)), ('M82W', np.float64(863.4)), ('R45F', np.float64(866.2)), ('T652P', np.float64(867.8)), ('E600W', np.float64(868.0)), ('L639R', np.float64(868.0)), ('E519S', np.float64(868.4)), ('E601L', np.float64(868.8)), ('S29W', np.float64(868.8)), ('L639I', np.float64(869.8)), ('T638R', np.float64(874.4)), ('T638I', np.float64(875.8)), ('R518S', np.float64(876.0)), ('E600L', np.float64(876.2)), ('E651P', np.float64(876.2)), ('H447F', np.float64(877.4)), ('E599W', np.float64(877.8)), ('R81F', np.float64(878.8)), ('D637R', np.float64(881.2)), ('L44F', np.float64(882.4)), ('D637I', np.float64(883.4)), ('R650P', np.float64(884.0)), ('E599L', np.float64(884.2)), ('Y598W', np.float64(887.2)), ('E636R', np.float64(888.4)), ('E636I', np.float64(890.4)), ('T516S', np.float64(892.0)), ('Y598L', np.float64(892.6)), ('A649P', np.float64(892.8)), ('S28W', np.float64(893.2)), ('G446F', np.float64(893.6)), ('V635R', np.float64(894.8)), ('L597W', np.float64(895.4)), ('M82F', np.float64(896.6)), ('V635I', np.float64(897.8)), ('R43F', np.float64(899.8)), ('F515S', np.float64(900.0)), ('V634R', np.float64(901.0)), ('N648P', np.float64(903.0)), ('K596W', np.float64(905.0)), ('V634I', np.float64(905.2)), ('K596L', np.float64(907.4)), ('F514S', np.float64(908.6)), ('Q633R', np.float64(909.2)), ('N445F', np.float64(911.4)), ('Q647P', np.float64(911.4)), ('Q633I', np.float64(913.4)), ('G595W', np.float64(914.2)), ('G595L', np.float64(914.4)), ('W632R', np.float64(915.6)), ('A83F', np.float64(915.8)), ('E513S', np.float64(915.8)), ('D27W', np.float64(920.0)), ('T646P', np.float64(921.2)), ('W632I', np.float64(921.8)), ('W594L', np.float64(922.8)), ('L631R', np.float64(923.8)), ('L512S', np.float64(924.2)), ('L631I', np.float64(927.8)), ('R444F', np.float64(928.6)), ('R593W', np.float64(929.8)), ('R593L', np.float64(930.0)), ('C630R', np.float64(930.4)), ('Y511S', np.float64(932.0)), ('C630I', np.float64(934.8)), ('E42F', np.float64(936.0)), ('R644P', np.float64(936.6)), ('N629R', np.float64(937.8)), ('E592L', np.float64(938.4)), ('A83W', np.float64(939.2)), ('E592W', np.float64(939.2)), ('N629I', np.float64(942.6)), ('A510S', np.float64(942.8)), ('A84F', np.float64(943.6)), ('N443F', np.float64(944.0)), ('D628R', np.float64(945.2)), ('I591L', np.float64(945.4)), ('N643P', np.float64(945.6)), ('K26W', np.float64(947.2)), ('I591W', np.float64(948.0)), ('D628I', np.float64(950.0)), ('K509S', np.float64(950.6)), ('L642P', np.float64(953.2)), ('L627R', np.float64(953.8)), ('W590L', np.float64(955.0)), ('L627I', np.float64(958.0)), ('Q508S', np.float64(959.4)), ('P626R', np.float64(961.0)), ('L641P', np.float64(962.2)), ('P442F', np.float64(962.6)), ('P626I', np.float64(965.4)), ('L589W', np.float64(965.8)), ('H41F', np.float64(967.4)), ('F625R', np.float64(969.2)), ('F507S', np.float64(969.6)), ('E640P', np.float64(971.2)), ('F625I', np.float64(972.6)), ('A588L', np.float64(973.2)), ('A588W', np.float64(974.6)), ('S25W', np.float64(975.4)), ('D624R', np.float64(976.6)), ('V506S', np.float64(978.4)), ('L639P', np.float64(979.4)), ('D624I', np.float64(980.8)), ('E441F', np.float64(980.8)), ('F587W', np.float64(982.8)), ('N623R', np.float64(983.2)), ('G85F', np.float64(983.8)), ('I496P', np.float64(984.4)), ('F587L', np.float64(984.6)), ('V497P', np.float64(984.6)), ('D494P', np.float64(988.0)), ('T638P', np.float64(988.0)), ('N623I', np.float64(988.2)), ('G498P', np.float64(988.4)), ('Y505S', np.float64(988.8)), ('A586W', np.float64(991.2)), ('S493P', np.float64(991.4)), ('D622R', np.float64(991.8)), ('W499P', np.float64(993.6)), ('A586L', np.float64(994.4)), ('S492P', np.float64(995.0)), ('D622I', np.float64(996.0)), ('D637P', np.float64(996.4)), ('R40F', np.float64(997.4)), ('G440F', np.float64(998.0)), ('V621R', np.float64(998.2)), ('G504S'

In [ ]:
#SANITY CHECK (Make sure there are none from current test set)

for mutant in greedyQueries:
  if mutant in trainSet:
    print(mutant)

In [ ]:
with open('query.txt', 'w') as f:
  for mutant in greedyQueries:
    f.write(mutant+'\n')